<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_R3t_QDsAEfCzS-usCnYC3g" name="MyDiagram" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_R3umUDsAEfCzS-usCnYC3g" name="Receção do Produto para Aprovisionamento">
      <elements xmi:type="process:StartEvent" xmi:id="_R3umUjsAEfCzS-usCnYC3g" name="Produto Recebido do Fornecedor" outgoing="_cnqeUDsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_R3vNYDsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_R3vNYTsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_R3vNYjsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_uG-qUDsAEfCzS-usCnYC3g" name="Verificar se os Produtos são os que estão no pedido" outgoing="_2Kw6kDsAEfCzS-usCnYC3g" incoming="_dKO_4DsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_uG-qUjsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_uG-qUTsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_uG-qUzsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_uG-qVDsAEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_uG_RYDsAEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uG_RYTsAEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_uG_RYzsAEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_uG_RYjsAEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_HO2tsDsBEfCzS-usCnYC3g" name="Encomenda Conforme?" outgoing="_H7WAQTsBEfCzS-usCnYC3g _SHXvYTsBEfCzS-usCnYC3g" incoming="_2Kw6kDsAEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_2KvscjsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_2KvscTsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_2KvsczsAEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_H7UyIDsBEfCzS-usCnYC3g" name="Verificar o tipo de produto" outgoing="_sWZoEDsBEfCzS-usCnYC3g" incoming="_H7WAQTsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_H7VZMTsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_H7VZMDsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_H7VZMjsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_H7VZMzsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_H7VZNDsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_H7VZNTsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_H7VZNzsBEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_H7VZNjsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_SHXIUDsBEfCzS-usCnYC3g" name="Recusar Receção da Encomenda" outgoing="_kFDc8TsBEfCzS-usCnYC3g" incoming="_SHXvYTsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_SHXIUjsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_SHXIUTsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_SHXIUzsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_SHXIVDsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_SHXIVTsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SHXIVjsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_SHXIWDsBEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_SHXIVzsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_lNAjgDsBEfCzS-usCnYC3g" name="Devolver Produto Não Conforme" outgoing="_IU_AlDsHEfCzS-usCnYC3g" incoming="_kFDc8TsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_kFC14jsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_kFC14TsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_kFC14zsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_kFC15DsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_kFC15TsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kFC15jsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_kFC16DsBEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_kFC15zsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_lNAjijsBEfCzS-usCnYC3g">
          <targetForm xmi:type="expression:Expression" xmi:id="_lNAjizsBEfCzS-usCnYC3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_lNAjiTsBEfCzS-usCnYC3g"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_lNAjjDsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_v2jVEDsBEfCzS-usCnYC3g" name="Verificar Visualmente as Embalagens Relacionadas" outgoing="_1MlloDsBEfCzS-usCnYC3g" incoming="_v2j8ITsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_v2jVEjsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_v2jVETsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_v2jVEzsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_v2jVFDsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_v2jVFTsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_v2jVFjsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_v2jVGDsBEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_v2jVFzsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_R15IYDsCEfCzS-usCnYC3g" name="Verificar a Qualidade do Produto" outgoing="_x1TO1DsDEfCzS-usCnYC3g" incoming="_R15vczsCEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_R15IYjsCEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_R15IYTsCEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_R15IYzsCEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_R15IZDsCEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_R15IZTsCEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_R15IZjsCEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_R15IaDsCEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_R15IZzsCEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_HNSVgDsDEfCzS-usCnYC3g" name="Receber Produto do Fornecedor" outgoing="_dKO_4DsBEfCzS-usCnYC3g" incoming="_cnqeUDsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_agA1UTsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_agA1UDsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_agA1UjsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_agA1UzsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_agA1VDsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_agA1VTsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_agA1VzsBEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_agA1VjsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_HNS8mTsDEfCzS-usCnYC3g">
          <targetForm xmi:type="expression:Expression" xmi:id="_HNS8mjsDEfCzS-usCnYC3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_HNS8mDsDEfCzS-usCnYC3g"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_HNS8mzsDEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="__FBYcDsDEfCzS-usCnYC3g" name="Tirar fotos e anexar à embalagem" outgoing="_JyBtsDsEEfCzS-usCnYC3g" incoming="__FCmkDsDEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="__FB_gTsDEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="__FB_gDsDEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="__FB_gjsDEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="__FB_gzsDEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="__FB_hDsDEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="__FB_hTsDEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="__FB_hzsDEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="__FB_hjsDEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_QcW3sDsEEfCzS-usCnYC3g" name="O Produto está em Bom Estadado?" outgoing="__FCmkDsDEfCzS-usCnYC3g _KP4uYDsEEfCzS-usCnYC3g _ug8QMDsFEfCzS-usCnYC3g" incoming="_x1TO1DsDEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_x1SnwjsDEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_x1SnwTsDEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_x1SnwzsDEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_Q2J3wDsEEfCzS-usCnYC3g" outgoing="_NMg3kDsEEfCzS-usCnYC3g" incoming="_JyBtsDsEEfCzS-usCnYC3g _KP4uYDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_JyBGoTsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_JyBGoDsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_JyBGojsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RMQDkDsEEfCzS-usCnYC3g" outgoing="_Yjc6pDsEEfCzS-usCnYC3g" incoming="_NMg3kDsEEfCzS-usCnYC3g _SsVWQDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_NMgQgTsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_NMgQgDsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_NMgQgjsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_YjcTkDsEEfCzS-usCnYC3g" name="Verificar se Tem Guia" outgoing="_q9sBUDsEEfCzS-usCnYC3g" incoming="_Yjc6pDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_YjcTkjsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_YjcTkTsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_YjcTkzsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_YjcTlDsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_YjcTlTsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YjcTljsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Yjc6oDsEEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_YjcTlzsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_u5fIgDsEEfCzS-usCnYC3g" name="Assinar na ferramenta utilizada (TPA p.e.)" outgoing="_zee9sDsEEfCzS-usCnYC3g" incoming="_u5fvkDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_u5fIgjsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_u5fIgTsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_u5fIgzsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_u5fIhDsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_u5fIhTsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_u5fIhjsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_u5fIiDsEEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_u5fIhzsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_xvmaADsEEfCzS-usCnYC3g" name="Assinar Guia do Fornecedor" outgoing="_226SGDsEEfCzS-usCnYC3g" incoming="_xvnBEzsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_xvmaAjsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_xvmaATsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_xvmaAzsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_xvmaBDsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_xvmaBTsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xvmaBjsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_xvmaCDsEEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_xvmaBzsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_zeeWoDsEEfCzS-usCnYC3g" name="Anexar as fotografias se existirem na Ferramenta (p.e TPA)" outgoing="_63w4YDsEEfCzS-usCnYC3g" incoming="_zee9sDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_zeeWojsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_zeeWoTsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_zeeWozsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_zeeWpDsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_zeeWpTsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zeeWpjsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_zeeWqDsEEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_zeeWpzsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_225rADsEEfCzS-usCnYC3g" name="Anexar as fotografias se existirem à guia" outgoing="_74J-YDsEEfCzS-usCnYC3g" incoming="_226SGDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_225rAjsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_225rATsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_225rAzsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_226SEDsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_226SETsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_226SEjsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_226SFDsEEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_226SEzsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_BGXvsDsFEfCzS-usCnYC3g" name="Verificar o Tipo de Guia a Emitir" outgoing="_P2cRwDsFEfCzS-usCnYC3g" incoming="_BGYWwDsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_BGXvsjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_BGXvsTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_BGXvszsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_BGXvtDsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_BGXvtTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BGXvtjsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_BGXvuDsFEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_BGXvtzsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_EgrTYDsFEfCzS-usCnYC3g" name="Guia de Remessa?" outgoing="_QukzoDsFEfCzS-usCnYC3g _TZUioDsFEfCzS-usCnYC3g" incoming="_P2cRwDsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EgrTYjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EgrTYTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EgrTYzsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_FCltoDsFEfCzS-usCnYC3g" outgoing="_BGYWwDsFEfCzS-usCnYC3g" incoming="_63w4YDsEEfCzS-usCnYC3g _74J-YDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_63wRUTsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_63wRUDsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_63wRUjsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_FaPYoDsFEfCzS-usCnYC3g" name="Encomenda Acompanhada de Documentação?" outgoing="_u5fvkDsEEfCzS-usCnYC3g _xvnBEzsEEfCzS-usCnYC3g" incoming="_q9sBUDsEEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_q9raQjsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_q9raQTsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_q9raQzsEEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_Gd-GgDsFEfCzS-usCnYC3g" name="Encomenda Danificada?" outgoing="_R15vczsCEfCzS-usCnYC3g _SsVWQDsEEfCzS-usCnYC3g" incoming="_1MlloDsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_1Mk-kjsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_1Mk-kTsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_1Mk-kzsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_HHkdIDsFEfCzS-usCnYC3g" name="Tipo de Produto" outgoing="_v2j8ITsBEfCzS-usCnYC3g _mVeDkDsFEfCzS-usCnYC3g" incoming="_sWZoEDsBEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_sWZBATsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_sWZBADsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_sWZBAjsBEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_QukMkDsFEfCzS-usCnYC3g" name="Emitir Guia de Remessa" outgoing="_WlfjtzsFEfCzS-usCnYC3g" incoming="_QukzoDsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_QukMkjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_QukMkTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_QukMkzsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_QukMlDsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_QukMlTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QukMljsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_QukMmDsFEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_QukMlzsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_SnNJMDsFEfCzS-usCnYC3g" name="Emitir Guia de Transporte" outgoing="_W7g3ADsFEfCzS-usCnYC3g" incoming="_TZUioDsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_SnNJMjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_SnNJMTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_SnNJMzsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_SnNJNDsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_SnNJNTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SnNJNjsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_SnNJODsFEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_SnNJNzsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_YAZbcDsFEfCzS-usCnYC3g" outgoing="_ZXhmeTsFEfCzS-usCnYC3g" incoming="_WlfjtzsFEfCzS-usCnYC3g _W7g3ADsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_WlfjsTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_WlfjsDsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_WlfjsjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_ZXg_YDsFEfCzS-usCnYC3g" name="Entregar uma via da guia" outgoing="_alOIqzsFEfCzS-usCnYC3g" incoming="_ZXhmeTsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZXg_YjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZXg_YTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ZXhmcDsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ZXhmcTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ZXhmcjsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZXhmczsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZXhmdTsFEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ZXhmdDsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_alNhkDsFEfCzS-usCnYC3g" name="Receber uma via da guia" outgoing="_6X1JMDsGEfCzS-usCnYC3g" incoming="_alOIqzsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_alOIoTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_alOIoDsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_alOIojsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_alOIozsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_alOIpDsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_alOIpTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_alOIpzsFEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_alOIpjsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_d7jLQDsFEfCzS-usCnYC3g" outgoing="_8hDfhDsGEfCzS-usCnYC3g" incoming="_mVeDkDsFEfCzS-usCnYC3g _6X1JMDsGEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7jyUTsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7jyUDsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_d7jyUjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_ug7pIDsFEfCzS-usCnYC3g" name="Devolver Produto Não Conforme" outgoing="_-mWYFzsGEfCzS-usCnYC3g" incoming="_ug8QMDsFEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ug7pIjsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ug7pITsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ug7pIzsFEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ug7pJDsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ug7pJTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ug7pJjsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ug7pKDsFEfCzS-usCnYC3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ug7pJzsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_8hC4cDsGEfCzS-usCnYC3g" name="Produto Recebido" incoming="_8hDfhDsGEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8hC4cjsGEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8hC4cTsGEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8hC4czsGEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_-mVxADsGEfCzS-usCnYC3g" name="Produto Recusado e não recebido" incoming="_-mWYFzsGEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_-mWYETsGEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_-mWYEDsGEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_-mWYEjsGEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_IU9ycDsHEfCzS-usCnYC3g" name="Devolver Produto Não Conforme" incoming="_IU_AlDsHEfCzS-usCnYC3g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_IU-ZgTsHEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_IU-ZgDsHEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_IU-ZgjsHEfCzS-usCnYC3g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:Data" xmi:id="_vtnmEDsCEfCzS-usCnYC3g" documentation="A encomenda está conforme? A encomenda está de acordo com o que foi pedido?" name="encomendaConforme" dataType="_R3vNiDsAEfCzS-usCnYC3g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_vtnmETsCEfCzS-usCnYC3g" name="encomendaConforme" content="encomendaConforme" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_R3vNcDsAEfCzS-usCnYC3g">
        <targetForm xmi:type="expression:Expression" xmi:id="_R3vNcTsAEfCzS-usCnYC3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_R3vNcjsAEfCzS-usCnYC3g">
        <targetForm xmi:type="expression:Expression" xmi:id="_R3vNczsAEfCzS-usCnYC3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2Kw6kDsAEfCzS-usCnYC3g" target="_HO2tsDsBEfCzS-usCnYC3g" source="_uG-qUDsAEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2Kw6kTsAEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_2Kw6kjsAEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_H7WAQTsBEfCzS-usCnYC3g" name="Sim" target="_H7UyIDsBEfCzS-usCnYC3g" source="_HO2tsDsBEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_H7WnUDsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_H7WnUTsBEfCzS-usCnYC3g" name="newScript()" content="encomendaConforme == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_Y6qWMDsDEfCzS-usCnYC3g" documentation="A encomenda está conforme? A encomenda está de acordo com o que foi pedido?" name="encomendaConforme" dataType="_R3vNiDsAEfCzS-usCnYC3g"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SHXvYTsBEfCzS-usCnYC3g" name="Não" target="_SHXIUDsBEfCzS-usCnYC3g" source="_HO2tsDsBEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SHXvYjsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_SHXvYzsBEfCzS-usCnYC3g" name="newScript()" content="encomendaConforme == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_XDupwDsDEfCzS-usCnYC3g" documentation="A encomenda está conforme? A encomenda está de acordo com o que foi pedido?" name="encomendaConforme" dataType="_R3vNiDsAEfCzS-usCnYC3g"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cnqeUDsBEfCzS-usCnYC3g" target="_HNSVgDsDEfCzS-usCnYC3g" source="_R3umUjsAEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cnqeUTsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_cnqeUjsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dKO_4DsBEfCzS-usCnYC3g" target="_uG-qUDsAEfCzS-usCnYC3g" source="_HNSVgDsDEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dKO_4TsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_dKO_4jsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kFDc8TsBEfCzS-usCnYC3g" target="_lNAjgDsBEfCzS-usCnYC3g" source="_SHXIUDsBEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kFDc8jsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_kFDc8zsBEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sWZoEDsBEfCzS-usCnYC3g" target="_HHkdIDsFEfCzS-usCnYC3g" source="_H7UyIDsBEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sWZoETsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_sWZoEjsBEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_v2j8ITsBEfCzS-usCnYC3g" name="Hardware" target="_v2jVEDsBEfCzS-usCnYC3g" source="_HHkdIDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_v2j8IjsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_v2j8IzsBEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1MlloDsBEfCzS-usCnYC3g" target="_Gd-GgDsFEfCzS-usCnYC3g" source="_v2jVEDsBEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1MlloTsBEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_1MllojsBEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_R15vczsCEfCzS-usCnYC3g" name="Sim" target="_R15IYDsCEfCzS-usCnYC3g" source="_Gd-GgDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_R15vdDsCEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_R15vdTsCEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x1TO1DsDEfCzS-usCnYC3g" target="_QcW3sDsEEfCzS-usCnYC3g" source="_R15IYDsCEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x1TO1TsDEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_x1TO1jsDEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__FCmkDsDEfCzS-usCnYC3g" name="Talvez" target="__FBYcDsDEfCzS-usCnYC3g" source="_QcW3sDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__FCmkTsDEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="__FCmkjsDEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JyBtsDsEEfCzS-usCnYC3g" target="_Q2J3wDsEEfCzS-usCnYC3g" source="__FBYcDsDEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JyBtsTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_JyBtsjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KP4uYDsEEfCzS-usCnYC3g" name="Sim" target="_Q2J3wDsEEfCzS-usCnYC3g" source="_QcW3sDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KP4uYTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_KP4uYjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NMg3kDsEEfCzS-usCnYC3g" target="_RMQDkDsEEfCzS-usCnYC3g" source="_Q2J3wDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NMg3kTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_NMg3kjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SsVWQDsEEfCzS-usCnYC3g" name="Não" target="_RMQDkDsEEfCzS-usCnYC3g" source="_Gd-GgDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SsVWQTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_SsVWQjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Yjc6pDsEEfCzS-usCnYC3g" target="_YjcTkDsEEfCzS-usCnYC3g" source="_RMQDkDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YjdhsDsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_YjdhsTsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q9sBUDsEEfCzS-usCnYC3g" target="_FaPYoDsFEfCzS-usCnYC3g" source="_YjcTkDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q9sBUTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_q9sBUjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_u5fvkDsEEfCzS-usCnYC3g" name="Não" target="_u5fIgDsEEfCzS-usCnYC3g" source="_FaPYoDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_u5fvkTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_u5fvkjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xvnBEzsEEfCzS-usCnYC3g" name="Sim" target="_xvmaADsEEfCzS-usCnYC3g" source="_FaPYoDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xvnBFDsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_xvnBFTsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zee9sDsEEfCzS-usCnYC3g" target="_zeeWoDsEEfCzS-usCnYC3g" source="_u5fIgDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zee9sTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_zee9sjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_226SGDsEEfCzS-usCnYC3g" target="_225rADsEEfCzS-usCnYC3g" source="_xvmaADsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_226SGTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_226SGjsEEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_63w4YDsEEfCzS-usCnYC3g" target="_FCltoDsFEfCzS-usCnYC3g" source="_zeeWoDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_63w4YTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_63w4YjsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_74J-YDsEEfCzS-usCnYC3g" target="_FCltoDsFEfCzS-usCnYC3g" source="_225rADsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_74J-YTsEEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_74J-YjsEEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BGYWwDsFEfCzS-usCnYC3g" target="_BGXvsDsFEfCzS-usCnYC3g" source="_FCltoDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BGYWwTsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_BGYWwjsFEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_P2cRwDsFEfCzS-usCnYC3g" target="_EgrTYDsFEfCzS-usCnYC3g" source="_BGXvsDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_P2cRwTsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_P2cRwjsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QukzoDsFEfCzS-usCnYC3g" target="_QukMkDsFEfCzS-usCnYC3g" source="_EgrTYDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QukzoTsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_QukzojsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TZUioDsFEfCzS-usCnYC3g" target="_SnNJMDsFEfCzS-usCnYC3g" source="_EgrTYDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TZVJsDsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_TZVJsTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WlfjtzsFEfCzS-usCnYC3g" target="_YAZbcDsFEfCzS-usCnYC3g" source="_QukMkDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WlfjuDsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_WlfjuTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_W7g3ADsFEfCzS-usCnYC3g" target="_YAZbcDsFEfCzS-usCnYC3g" source="_SnNJMDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_W7heEDsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_W7heETsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZXhmeTsFEfCzS-usCnYC3g" target="_ZXg_YDsFEfCzS-usCnYC3g" source="_YAZbcDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZXhmejsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZXhmezsFEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_alOIqzsFEfCzS-usCnYC3g" target="_alNhkDsFEfCzS-usCnYC3g" source="_ZXg_YDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_alOIrDsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_alOIrTsFEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mVeDkDsFEfCzS-usCnYC3g" name="Software" target="_d7jLQDsFEfCzS-usCnYC3g" source="_HHkdIDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mVeqoDsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_mVeqoTsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ug8QMDsFEfCzS-usCnYC3g" name="Não" target="_ug7pIDsFEfCzS-usCnYC3g" source="_QcW3sDsEEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ug8QMTsFEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_ug8QMjsFEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6X1JMDsGEfCzS-usCnYC3g" target="_d7jLQDsFEfCzS-usCnYC3g" source="_alNhkDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6X1wQDsGEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_6X1wQTsGEfCzS-usCnYC3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8hDfhDsGEfCzS-usCnYC3g" target="_8hC4cDsGEfCzS-usCnYC3g" source="_d7jLQDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8hDfhTsGEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_8hDfhjsGEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-mWYFzsGEfCzS-usCnYC3g" target="_-mVxADsGEfCzS-usCnYC3g" source="_ug7pIDsFEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-mW_IDsGEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_-mW_ITsGEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IU_AlDsHEfCzS-usCnYC3g" target="_IU9ycDsHEfCzS-usCnYC3g" source="_lNAjgDsBEfCzS-usCnYC3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IU_AlTsHEfCzS-usCnYC3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_IU_AljsHEfCzS-usCnYC3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_R3vNdzsAEfCzS-usCnYC3g" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_R3vNeDsAEfCzS-usCnYC3g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_R3vNeTsAEfCzS-usCnYC3g">
        <name xmi:type="expression:Expression" xmi:id="_R3vNejsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_R3vNezsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_R3vNfDsAEfCzS-usCnYC3g">
        <name xmi:type="expression:Expression" xmi:id="_R3vNfTsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_R3vNfjsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_R3vNfzsAEfCzS-usCnYC3g">
        <name xmi:type="expression:Expression" xmi:id="_R3vNgDsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_R3vNgTsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_R3vNgjsAEfCzS-usCnYC3g">
        <name xmi:type="expression:Expression" xmi:id="_R3vNgzsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_R3vNhDsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_R3vNhTsAEfCzS-usCnYC3g">
        <name xmi:type="expression:Expression" xmi:id="_R3vNhjsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_R3vNhzsAEfCzS-usCnYC3g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_R3vNiDsAEfCzS-usCnYC3g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_R3vNiTsAEfCzS-usCnYC3g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_R3vNijsAEfCzS-usCnYC3g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_R3vNizsAEfCzS-usCnYC3g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_R3vNjDsAEfCzS-usCnYC3g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_R3vNjTsAEfCzS-usCnYC3g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_R3vNjjsAEfCzS-usCnYC3g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_R3vNjzsAEfCzS-usCnYC3g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_R3vNkDsAEfCzS-usCnYC3g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_R3vNkTsAEfCzS-usCnYC3g" type="Process" element="_R3t_QDsAEfCzS-usCnYC3g" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_R3vNkjsAEfCzS-usCnYC3g" type="2007" element="_R3umUDsAEfCzS-usCnYC3g">
      <children xmi:type="notation:DecorationNode" xmi:id="_R3vNkzsAEfCzS-usCnYC3g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_R3vNlDsAEfCzS-usCnYC3g" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_R3vNmzsAEfCzS-usCnYC3g" type="3002" element="_R3umUjsAEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_R3vNnDsAEfCzS-usCnYC3g" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_R3vNnTsAEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R3vNnjsAEfCzS-usCnYC3g" x="103" y="355"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_uG_RZDsAEfCzS-usCnYC3g" type="3027" element="_uG-qUDsAEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_uG_RZjsAEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uG_RZTsAEfCzS-usCnYC3g" x="369" y="335" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_HO3UwzsBEfCzS-usCnYC3g" type="3008" element="_HO2tsDsBEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_HO370DsBEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_HO370TsBEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HO3UxDsBEfCzS-usCnYC3g" x="556" y="348" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_H7VZODsBEfCzS-usCnYC3g" type="3027" element="_H7UyIDsBEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_H7WAQDsBEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H7VZOTsBEfCzS-usCnYC3g" x="645" y="236" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_SHXIWTsBEfCzS-usCnYC3g" type="3027" element="_SHXIUDsBEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_SHXvYDsBEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SHXIWjsBEfCzS-usCnYC3g" x="656" y="436" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_lNAjjTsBEfCzS-usCnYC3g" type="3005" element="_lNAjgDsBEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_lNAjjzsBEfCzS-usCnYC3g" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lNAjjjsBEfCzS-usCnYC3g" x="3627" y="436" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_v2jVGTsBEfCzS-usCnYC3g" type="3027" element="_v2jVEDsBEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_v2j8IDsBEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_v2jVGjsBEfCzS-usCnYC3g" x="968" y="234" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_R15vcDsCEfCzS-usCnYC3g" type="3027" element="_R15IYDsCEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_R15vcjsCEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R15vcTsCEfCzS-usCnYC3g" x="1281" y="232" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_HNS8nDsDEfCzS-usCnYC3g" type="3005" element="_HNSVgDsDEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_HNS8njsDEfCzS-usCnYC3g" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HNS8nTsDEfCzS-usCnYC3g" x="217" y="340" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="__FB_iDsDEfCzS-usCnYC3g" type="3027" element="__FBYcDsDEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="__FB_ijsDEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__FB_iTsDEfCzS-usCnYC3g" x="1623" y="238" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_QcXewzsEEfCzS-usCnYC3g" type="3008" element="_QcW3sDsEEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_QcXexTsEEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_QcXexjsEEfCzS-usCnYC3g" y="11"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QcXexDsEEfCzS-usCnYC3g" x="1497" y="240" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Q2Ke0zsEEfCzS-usCnYC3g" type="3008" element="_Q2J3wDsEEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q2Ke1TsEEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Q2Ke1jsEEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q2Ke1DsEEfCzS-usCnYC3g" x="1790" y="241" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RMQDlDsEEfCzS-usCnYC3g" type="3008" element="_RMQDkDsEEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RMQDljsEEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RMQqoDsEEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RMQDlTsEEfCzS-usCnYC3g" x="1889" y="242" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Yjc6oTsEEfCzS-usCnYC3g" type="3027" element="_YjcTkDsEEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_Yjc6ozsEEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Yjc6ojsEEfCzS-usCnYC3g" x="1984" y="235" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_u5fIiTsEEfCzS-usCnYC3g" type="3027" element="_u5fIgDsEEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_u5fIizsEEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_u5fIijsEEfCzS-usCnYC3g" x="2302" y="158"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_xvnBEDsEEfCzS-usCnYC3g" type="3027" element="_xvmaADsEEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_xvnBEjsEEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xvnBETsEEfCzS-usCnYC3g" x="2305" y="276"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_zeeWqTsEEfCzS-usCnYC3g" type="3027" element="_zeeWoDsEEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_zeeWqzsEEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zeeWqjsEEfCzS-usCnYC3g" x="2478" y="158" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_226SFTsEEfCzS-usCnYC3g" type="3027" element="_225rADsEEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_226SFzsEEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_226SFjsEEfCzS-usCnYC3g" x="2482" y="276" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_BGXvuTsFEfCzS-usCnYC3g" type="3027" element="_BGXvsDsFEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_BGXvuzsFEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BGXvujsFEfCzS-usCnYC3g" x="2794" y="225" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Egr6cDsFEfCzS-usCnYC3g" type="3008" element="_EgrTYDsFEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Egr6cjsFEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Egr6czsFEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Egr6cTsFEfCzS-usCnYC3g" x="2953" y="233"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_FCmUsjsFEfCzS-usCnYC3g" type="3008" element="_FCltoDsFEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_FCmUtDsFEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_FCmUtTsFEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FCmUszsFEfCzS-usCnYC3g" x="2697" y="228" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_FaPYpDsFEfCzS-usCnYC3g" type="3008" element="_FaPYoDsFEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_FaPYpjsFEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_FaPYpzsFEfCzS-usCnYC3g" x="-44" y="-70"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FaPYpTsFEfCzS-usCnYC3g" x="2162" y="241" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Gd-tkzsFEfCzS-usCnYC3g" type="3008" element="_Gd-GgDsFEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Gd-tlTsFEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Gd-tljsFEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Gd-tlDsFEfCzS-usCnYC3g" x="1148" y="244" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_HHlEMDsFEfCzS-usCnYC3g" type="3008" element="_HHkdIDsFEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_HHlEMjsFEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_HHlEMzsFEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HHlEMTsFEfCzS-usCnYC3g" x="855" y="242" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_QukMmTsFEfCzS-usCnYC3g" type="3027" element="_QukMkDsFEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_QukMmzsFEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QukMmjsFEfCzS-usCnYC3g" x="3095" y="153" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_SnNwQDsFEfCzS-usCnYC3g" type="3006" element="_SnNJMDsFEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_SnNwQjsFEfCzS-usCnYC3g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SnNwQTsFEfCzS-usCnYC3g" x="3095" y="302" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_YAZbdDsFEfCzS-usCnYC3g" type="3008" element="_YAZbcDsFEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_YAaCgDsFEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_YAaCgTsFEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YAZbdTsFEfCzS-usCnYC3g" x="3273" y="236" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ZXhmdjsFEfCzS-usCnYC3g" type="3027" element="_ZXg_YDsFEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_ZXhmeDsFEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZXhmdzsFEfCzS-usCnYC3g" x="3403" y="220" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_alOIqDsFEfCzS-usCnYC3g" type="3027" element="_alNhkDsFEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_alOIqjsFEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_alOIqTsFEfCzS-usCnYC3g" x="3617" y="233" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_d7jyUzsFEfCzS-usCnYC3g" type="3008" element="_d7jLQDsFEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_d7kZYDsFEfCzS-usCnYC3g" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_d7kZYTsFEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_d7jyVDsFEfCzS-usCnYC3g" x="3783" y="241"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ug7pKTsFEfCzS-usCnYC3g" type="3027" element="_ug7pIDsFEfCzS-usCnYC3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_ug7pKzsFEfCzS-usCnYC3g" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ug7pKjsFEfCzS-usCnYC3g" x="3627" y="361" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_8hDfgDsGEfCzS-usCnYC3g" type="3003" element="_8hC4cDsGEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_8hDfgjsGEfCzS-usCnYC3g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_8hDfgzsGEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8hDfgTsGEfCzS-usCnYC3g" x="4016" y="252"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_-mWYEzsGEfCzS-usCnYC3g" type="3003" element="_-mVxADsGEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_-mWYFTsGEfCzS-usCnYC3g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_-mWYFjsGEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-mWYFDsGEfCzS-usCnYC3g" x="4015" y="373"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_IU_AkDsHEfCzS-usCnYC3g" type="3003" element="_IU9ycDsHEfCzS-usCnYC3g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_IU_AkjsHEfCzS-usCnYC3g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_IU_AkzsHEfCzS-usCnYC3g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IU_AkTsHEfCzS-usCnYC3g" x="4019" y="455"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_R3vNpDsAEfCzS-usCnYC3g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_R3vNpTsAEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_R3vNpjsAEfCzS-usCnYC3g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_R3vNpzsAEfCzS-usCnYC3g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R3vNqDsAEfCzS-usCnYC3g" width="4225" height="700"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_R3vNqTsAEfCzS-usCnYC3g"/>
    <edges xmi:type="notation:Connector" xmi:id="_2KxhoDsAEfCzS-usCnYC3g" type="4001" element="_2Kw6kDsAEfCzS-usCnYC3g" source="_uG_RZDsAEfCzS-usCnYC3g" target="_HO3UwzsBEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2KxhozsAEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2KxhpDsAEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2KxhoTsAEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2KxhojsAEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_H7WnUjsBEfCzS-usCnYC3g" type="4001" element="_H7WAQTsBEfCzS-usCnYC3g" source="_HO3UwzsBEfCzS-usCnYC3g" target="_H7VZODsBEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_H7WnVTsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_H7WnVjsBEfCzS-usCnYC3g" x="17" y="21"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_H7WnUzsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_H7WnVDsBEfCzS-usCnYC3g" points="[1, -21, -74, 100]$[1, -102, -74, 19]$[68, -102, -7, 19]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JJ0lkDsBEfCzS-usCnYC3g" id="(0.06,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SHXvZDsBEfCzS-usCnYC3g" type="4001" element="_SHXvYTsBEfCzS-usCnYC3g" source="_HO3UwzsBEfCzS-usCnYC3g" target="_SHXIWTsBEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SHYWcDsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SHYWcTsBEfCzS-usCnYC3g" x="-21" y="-23"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SHXvZTsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SHXvZjsBEfCzS-usCnYC3g" points="[0, 22, -139, -75]$[0, 100, -139, 3]$[79, 100, -60, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cnrFYDsBEfCzS-usCnYC3g" type="4001" element="_cnqeUDsBEfCzS-usCnYC3g" source="_R3vNmzsAEfCzS-usCnYC3g" target="_HNS8nDsDEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cnrFYzsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cnrFZDsBEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cnrFYTsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cnrFYjsBEfCzS-usCnYC3g" points="[-4, -5, -102, -136]$[93, 130, -5, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cnsTgDsBEfCzS-usCnYC3g" id="(1.0,0.9333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cnsTgTsBEfCzS-usCnYC3g" id="(0.041666666666666664,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dKPm8DsBEfCzS-usCnYC3g" type="4001" element="_dKO_4DsBEfCzS-usCnYC3g" source="_HNS8nDsDEfCzS-usCnYC3g" target="_uG_RZDsAEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dKPm8zsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dKPm9DsBEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dKPm8TsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dKPm8jsBEfCzS-usCnYC3g" points="[0, 1, -82, 0]$[67, 0, -15, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dKRcIDsBEfCzS-usCnYC3g" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dKRcITsBEfCzS-usCnYC3g" id="(0.10714285714285714,0.4714285714285714)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kFEEADsBEfCzS-usCnYC3g" type="4001" element="_kFDc8TsBEfCzS-usCnYC3g" source="_SHXIWTsBEfCzS-usCnYC3g" target="_lNAjjTsBEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kFEEAzsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kFEEBDsBEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kFEEATsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kFEEAjsBEfCzS-usCnYC3g" points="[60, 2, -2911, 2]$[2911, 2, -60, 2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sWZoEzsBEfCzS-usCnYC3g" type="4001" element="_sWZoEDsBEfCzS-usCnYC3g" source="_H7VZODsBEfCzS-usCnYC3g" target="_HHlEMDsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sWaPIDsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sWaPITsBEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sWZoFDsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sWZoFTsBEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_v2kjMDsBEfCzS-usCnYC3g" type="4001" element="_v2j8ITsBEfCzS-usCnYC3g" source="_HHlEMDsFEfCzS-usCnYC3g" target="_v2jVGTsBEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_v2kjMzsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_v2kjNDsBEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_v2kjMTsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_v2kjMjsBEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1MllozsBEfCzS-usCnYC3g" type="4001" element="_1MlloDsBEfCzS-usCnYC3g" source="_v2jVGTsBEfCzS-usCnYC3g" target="_Gd-tkzsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1MllpjsBEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1MllpzsBEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1MllpDsBEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1MllpTsBEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_R16WgDsCEfCzS-usCnYC3g" type="4001" element="_R15vczsCEfCzS-usCnYC3g" source="_Gd-tkzsFEfCzS-usCnYC3g" target="_R15vcDsCEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_R16WgzsCEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_R16WhDsCEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_R16WgTsCEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_R16WgjsCEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x1TO1zsDEfCzS-usCnYC3g" type="4001" element="_x1TO1DsDEfCzS-usCnYC3g" source="_R15vcDsCEfCzS-usCnYC3g" target="_QcXewzsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x1T14jsDEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x1T14zsDEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x1T14DsDEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x1T14TsDEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__FCmkzsDEfCzS-usCnYC3g" type="4001" element="__FCmkDsDEfCzS-usCnYC3g" source="_QcXewzsEEfCzS-usCnYC3g" target="__FB_iDsDEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__FCmljsDEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__FCmlzsDEfCzS-usCnYC3g" x="-18" y="-12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__FCmlDsDEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__FCmlTsDEfCzS-usCnYC3g" points="[22, 0, -143, -7]$[105, 0, -60, -7]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JyBtszsEEfCzS-usCnYC3g" type="4001" element="_JyBtsDsEEfCzS-usCnYC3g" source="__FB_iDsDEfCzS-usCnYC3g" target="_Q2Ke0zsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JyBttjsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JyBttzsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JyBttDsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JyBttTsEEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KP5VcDsEEfCzS-usCnYC3g" type="4001" element="_KP4uYDsEEfCzS-usCnYC3g" source="_QcXewzsEEfCzS-usCnYC3g" target="_Q2Ke0zsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KP5VczsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KP5VdDsEEfCzS-usCnYC3g" x="-148" y="-12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KP5VcTsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KP5VcjsEEfCzS-usCnYC3g" points="[-22, -24, -293, -22]$[-22, -85, -293, -83]$[271, -85, 0, -83]$[271, -23, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KP7KoDsEEfCzS-usCnYC3g" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NMg3kzsEEfCzS-usCnYC3g" type="4001" element="_NMg3kDsEEfCzS-usCnYC3g" source="_Q2Ke0zsEEfCzS-usCnYC3g" target="_RMQDlDsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NMg3ljsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NMg3lzsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NMg3lDsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NMg3lTsEEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SsV9UDsEEfCzS-usCnYC3g" type="4001" element="_SsVWQDsEEfCzS-usCnYC3g" source="_Gd-tkzsFEfCzS-usCnYC3g" target="_RMQDlDsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SsV9UzsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SsV9VDsEEfCzS-usCnYC3g" x="-359" y="102"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SsV9UTsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SsV9UjsEEfCzS-usCnYC3g" points="[-22, -24, -741, -19]$[-22, -192, -741, -187]$[719, -192, 0, -187]$[719, -26, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SsXLcDsEEfCzS-usCnYC3g" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YjdhsjsEEfCzS-usCnYC3g" type="4001" element="_Yjc6pDsEEfCzS-usCnYC3g" source="_RMQDlDsEEfCzS-usCnYC3g" target="_Yjc6oTsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YjeIwDsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YjeIwTsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YjdhszsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YjdhtDsEEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q9sBUzsEEfCzS-usCnYC3g" type="4001" element="_q9sBUDsEEfCzS-usCnYC3g" source="_Yjc6oTsEEfCzS-usCnYC3g" target="_FaPYpDsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q9sBVjsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q9sBVzsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q9sBVDsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q9sBVTsEEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_u5fvkzsEEfCzS-usCnYC3g" type="4001" element="_u5fvkDsEEfCzS-usCnYC3g" source="_FaPYpDsFEfCzS-usCnYC3g" target="_u5fIiTsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_u5fvljsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_u5fvlzsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_u5fvlDsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_u5fvlTsEEfCzS-usCnYC3g" points="[0, -21, -169, 58]$[0, -72, -169, 7]$[119, -72, -50, 7]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xvnoIDsEEfCzS-usCnYC3g" type="4001" element="_xvnBEzsEEfCzS-usCnYC3g" source="_FaPYpDsFEfCzS-usCnYC3g" target="_xvnBEDsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xvnoIzsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xvnoJDsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xvnoITsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xvnoIjsEEfCzS-usCnYC3g" points="[0, 22, -172, -17]$[0, 42, -172, 3]$[122, 42, -50, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zee9szsEEfCzS-usCnYC3g" type="4001" element="_zee9sDsEEfCzS-usCnYC3g" source="_u5fIiTsEEfCzS-usCnYC3g" target="_zeeWqTsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zee9tjsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zee9tzsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zee9tDsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zee9tTsEEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2265IDsEEfCzS-usCnYC3g" type="4001" element="_226SGDsEEfCzS-usCnYC3g" source="_xvnBEDsEEfCzS-usCnYC3g" target="_226SFTsEEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2265IzsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2265JDsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2265ITsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2265IjsEEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_63w4YzsEEfCzS-usCnYC3g" type="4001" element="_63w4YDsEEfCzS-usCnYC3g" source="_zeeWqTsEEfCzS-usCnYC3g" target="_FCmUsjsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_63w4ZjsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_63w4ZzsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_63w4ZDsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_63w4ZTsEEfCzS-usCnYC3g" points="[70, -11, -100, -68]$[170, -11, 0, -68]$[170, 36, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_74LMgDsEEfCzS-usCnYC3g" type="4001" element="_74J-YDsEEfCzS-usCnYC3g" source="_226SFTsEEfCzS-usCnYC3g" target="_FCmUsjsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_74LMgzsEEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_74LMhDsEEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_74LMgTsEEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_74LMgjsEEfCzS-usCnYC3g" points="[0, 0, -96, 50]$[96, 0, 0, 50]$[96, -28, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_74MaoDsEEfCzS-usCnYC3g" id="(1.0,0.34285714285714286)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BGYWwzsFEfCzS-usCnYC3g" type="4001" element="_BGYWwDsFEfCzS-usCnYC3g" source="_FCmUsjsFEfCzS-usCnYC3g" target="_BGXvuTsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BGYWxjsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BGYWxzsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BGYWxDsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BGYWxTsFEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_P2c40DsFEfCzS-usCnYC3g" type="4001" element="_P2cRwDsFEfCzS-usCnYC3g" source="_BGXvuTsFEfCzS-usCnYC3g" target="_Egr6cDsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_P2c40zsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_P2c41DsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_P2c40TsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_P2c40jsFEfCzS-usCnYC3g" points="[0, 4, -75, 0]$[77, 4, 2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_P2eG8DsFEfCzS-usCnYC3g" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_P2eG8TsFEfCzS-usCnYC3g" id="(0.8372093023255814,0.5813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QukzozsFEfCzS-usCnYC3g" type="4001" element="_QukzoDsFEfCzS-usCnYC3g" source="_Egr6cDsFEfCzS-usCnYC3g" target="_QukMmTsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QukzpjsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QukzpzsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QukzpDsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QukzpTsFEfCzS-usCnYC3g" points="[-2, -19, -183, 52]$[-2, -72, -183, -1]$[121, -72, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TZb3YDsFEfCzS-usCnYC3g" type="4001" element="_TZUioDsFEfCzS-usCnYC3g" source="_Egr6cDsFEfCzS-usCnYC3g" target="_SnNwQDsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TZcecDsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TZcecTsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TZb3YTsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TZb3YjsFEfCzS-usCnYC3g" points="[-22, 10, -125, -56]$[-22, 63, -125, -3]$[99, 63, -4, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TZdFgDsFEfCzS-usCnYC3g" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TZdFgTsFEfCzS-usCnYC3g" id="(0.03333333333333333,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WlfjujsFEfCzS-usCnYC3g" type="4001" element="_WlfjtzsFEfCzS-usCnYC3g" source="_QukMmTsFEfCzS-usCnYC3g" target="_YAZbdDsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WlgKwDsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WlgKwTsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WlfjuzsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WlfjvDsFEfCzS-usCnYC3g" points="[60, -1, -79, -75]$[139, -1, 0, -75]$[139, 53, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_W7heEjsFEfCzS-usCnYC3g" type="4001" element="_W7g3ADsFEfCzS-usCnYC3g" source="_SnNwQDsFEfCzS-usCnYC3g" target="_YAZbdDsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_W7iFIDsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_W7iFITsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_W7heEzsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_W7heFDsFEfCzS-usCnYC3g" points="[0, 0, -79, 76]$[79, 0, 0, 76]$[79, -54, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_W7jTQDsFEfCzS-usCnYC3g" id="(1.0,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZXhmfDsFEfCzS-usCnYC3g" type="4001" element="_ZXhmeTsFEfCzS-usCnYC3g" source="_YAZbdDsFEfCzS-usCnYC3g" target="_ZXhmdjsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZXhmfzsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZXhmgDsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZXhmfTsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZXhmfjsFEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_alOvsDsFEfCzS-usCnYC3g" type="4001" element="_alOIqzsFEfCzS-usCnYC3g" source="_ZXhmdjsFEfCzS-usCnYC3g" target="_alOIqDsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_alOvszsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_alOvtDsFEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_alOvsTsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_alOvsjsFEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mVkKMDsFEfCzS-usCnYC3g" type="4001" element="_mVeDkDsFEfCzS-usCnYC3g" source="_HHlEMDsFEfCzS-usCnYC3g" target="_d7jyUzsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mVkxQDsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mVkxQTsFEfCzS-usCnYC3g" x="-1440" y="146"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mVkKMTsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mVkKMjsFEfCzS-usCnYC3g" points="[-22, -26, -2928, -20]$[-22, -249, -2928, -243]$[2906, -249, 0, -243]$[2906, -27, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mVlYUDsFEfCzS-usCnYC3g" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ug8QMzsFEfCzS-usCnYC3g" type="4001" element="_ug8QMDsFEfCzS-usCnYC3g" source="_QcXewzsEEfCzS-usCnYC3g" target="_ug7pKTsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ug8QNjsFEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ug8QNzsFEfCzS-usCnYC3g" x="-967" y="-31"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ug8QNDsFEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ug8QNTsFEfCzS-usCnYC3g" points="[0, 22, -2159, -127]$[0, 132, -2159, -17]$[2109, 132, -50, -17]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6X1wQjsGEfCzS-usCnYC3g" type="4001" element="_6X1JMDsGEfCzS-usCnYC3g" source="_alOIqDsFEfCzS-usCnYC3g" target="_d7jyUzsFEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6X2XUDsGEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6X2XUTsGEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6X1wQzsGEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6X1wRDsGEfCzS-usCnYC3g" points="[0, -4, -67, -3]$[62, -17, -5, -16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6X3lcDsGEfCzS-usCnYC3g" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8hEGkDsGEfCzS-usCnYC3g" type="4001" element="_8hDfhDsGEfCzS-usCnYC3g" source="_d7jyUzsFEfCzS-usCnYC3g" target="_8hDfgDsGEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8hEGkzsGEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8hEGlDsGEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8hEGkTsGEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8hEGkjsGEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-mW_IjsGEfCzS-usCnYC3g" type="4001" element="_-mWYFzsGEfCzS-usCnYC3g" source="_ug7pKTsFEfCzS-usCnYC3g" target="_-mWYEzsGEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-mW_JTsGEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-mW_JjsGEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-mW_IzsGEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-mW_JDsGEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IU_AlzsHEfCzS-usCnYC3g" type="4001" element="_IU_AlDsHEfCzS-usCnYC3g" source="_lNAjjTsBEfCzS-usCnYC3g" target="_IU_AkDsHEfCzS-usCnYC3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IU_AmjsHEfCzS-usCnYC3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IU_AmzsHEfCzS-usCnYC3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IU_AmDsHEfCzS-usCnYC3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IU_AmTsHEfCzS-usCnYC3g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
