<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_SPTwIDsREfCFwZ2i48Dr6Q" name="Prepracaodeproduto - 1.0" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_SRhWoDsREfCFwZ2i48Dr6Q" name="Preparação de Produto">
      <elements xmi:type="process:Lane" xmi:id="_SWNCUDsREfCFwZ2i48Dr6Q" name="Responsável Lane" actor="__ebUQE1JEfCo_IWfKKhhfw">
        <elements xmi:type="process:XORGateway" xmi:id="_SX1aADsREfCFwZ2i48Dr6Q" name="Qual é o contexto da Encomenda?" outgoing="_SfBnIDsREfCFwZ2i48Dr6Q _SfQ3sDsREfCFwZ2i48Dr6Q" incoming="_Sh-0gDsREfCFwZ2i48Dr6Q _86foYE3MEfCRZeFygNlKAA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SX2BETsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SX2BEDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SX2BEjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_SYEDgDsREfCFwZ2i48Dr6Q" name="É para Leiria sem cliente atribuido?" outgoing="_Sf5w4DsREfCFwZ2i48Dr6Q _SgEI8DsREfCFwZ2i48Dr6Q" incoming="_SfuKsDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SYEqkTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SYEqkDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SYEqkjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_SYRe4DsREfCFwZ2i48Dr6Q" name="_iJ9P8DsGEfC5SYqfsyMQTA" outgoing="_Sgm7gDsREfCFwZ2i48Dr6Q" incoming="_SgPIEDsREfCFwZ2i48Dr6Q _SgauQDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SYSF8TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SYSF8DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SYSF8jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_SYbP4DsREfCFwZ2i48Dr6Q" name="_pS7dwDsGEfC5SYqfsyMQTA" outgoing="_Sg_WADsREfCFwZ2i48Dr6Q" incoming="_Sgm7gDsREfCFwZ2i48Dr6Q _SgyhsDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SYb28TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SYb28DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SYb28jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_SYkZ0DsREfCFwZ2i48Dr6Q" name="_EDPP0DsNEfC5SYqfsyMQTA" outgoing="_Shly8DsREfCFwZ2i48Dr6Q _odJs0E1QEfCo_IWfKKhhfw" incoming="_nQvkEE1QEfCo_IWfKKhhfw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SYlA4TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SYlA4DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SYlA4jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_SY370DsREfCFwZ2i48Dr6Q" name="Os componentes estão todos rececionados?" outgoing="_Sh-0gDsREfCFwZ2i48Dr6Q _SiM28DsREfCFwZ2i48Dr6Q" incoming="_ShynQDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SY4i4TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SY4i4DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SY4i4jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SZBs0DsREfCFwZ2i48Dr6Q" name="Colocar Etiqueta P" outgoing="_SgyhsDsREfCFwZ2i48Dr6Q" incoming="_SfBnIDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SZCT4TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SZCT4DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SZCT4jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_ot73oE1MEfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ot9FwE1MEfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pYJSQE1MEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ot9FwU1MEfCo_IWfKKhhfw" name="newScript()" content="businessOrder.tipo_etiqueta = &quot;p&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_NYSfsE1NEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ot9s0E1MEfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setTipo_etiqueta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SZCT4zsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SZCT5DsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SZCT5TsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SZCT5zsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SZCT5jsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SZIagDsREfCFwZ2i48Dr6Q" name="Colocar Etiqueta S, produto na caixa, descrição e delegação-destino" outgoing="_SfikgDsREfCFwZ2i48Dr6Q" incoming="_SfQ3sDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SZIagjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SZIagTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SZIagzsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_OGCWgE1NEfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_OGC9kE1NEfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O8ju0E1NEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_OGC9kU1NEfCo_IWfKKhhfw" name="newScript()" content="businessOrder.tipo_etiqueta = &quot;s&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UqQ4gE1NEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_OGC9kk1NEfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setTipo_etiqueta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SZIahDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SZIahTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SZIahjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SZIaiDsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SZIahzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SZZgQDsREfCFwZ2i48Dr6Q" name="Colocar Etiqueta A2" outgoing="_SgPIEDsREfCFwZ2i48Dr6Q" incoming="_Sf5w4DsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SZZgQjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SZZgQTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SZZgQzsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_LYqU0E1OEfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_LYq74E1OEfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_L53kcE1OEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_LYq74U1OEfCo_IWfKKhhfw" name="newScript()" content="businessOrder.tipo_etiqueta = &quot;s-a2&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O4w-gE1OEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_LYq74k1OEfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setTipo_etiqueta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SZZgRDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SZZgRTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SZZgRjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SZZgSDsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SZZgRzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SZj4UDsREfCFwZ2i48Dr6Q" name="Colocar Etiqueta A5" outgoing="_SgauQDsREfCFwZ2i48Dr6Q" incoming="_SgEI8DsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SZj4UjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SZj4UTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SZj4UzsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_PUM9UE1OEfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PUM9UU1OEfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Po2XoE1OEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PUM9Uk1OEfCo_IWfKKhhfw" name="newScript()" content="businessOrder.tipo_etiqueta = &quot;s-a5&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Te6qQE1OEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PUM9U01OEfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setTipo_etiqueta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SZj4VDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SZj4VTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SZj4VjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SZj4WDsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SZj4VzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SZu3cDsREfCFwZ2i48Dr6Q" name="Indicar no sistema que o produto está em fase de preparação" outgoing="_nQvkEE1QEfCo_IWfKKhhfw" incoming="_Sg_WADsREfCFwZ2i48Dr6Q" actor="__ebUQE1JEfCo_IWfKKhhfw" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SZvegTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SZvegDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SZvegjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_l_MHgE1OEfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_l_MHgU1OEfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_l_MHgk1OEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_l_MHg01OEfCo_IWfKKhhfw" name="businessOrderInput.estado" content="businessOrderInput?.estado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_l_MHhE1OEfCo_IWfKKhhfw" name="businessOrderInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_l_MHhU1OEfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setEstado">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SZvegzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SZvehDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SZvehTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SZvehzsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SZvehjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SZveiTsREfCFwZ2i48Dr6Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_U7AYUE1PEfCo_IWfKKhhfw" name="encoemdaempreparacao" content="cb9749ab-4f91-45c6-9cfe-4cf6ae72c3bf" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SZveiDsREfCFwZ2i48Dr6Q">
            <inputs xmi:type="process:ContractInput" xmi:id="_l_C9kE1OEfCo_IWfKKhhfw" name="businessOrderInput" type="COMPLEX" dataReference="businessOrder" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_l_ELsE1OEfCo_IWfKKhhfw" name="estado" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SZveizsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_SZ7rwDsREfCFwZ2i48Dr6Q" name="Passar o produto ao responsável de assistência Técnica" outgoing="_pI6moE1QEfCo_IWfKKhhfw" incoming="_odJs0E1QEfCo_IWfKKhhfw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SZ8S0TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SZ8S0DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SZ8S0jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SZ8S0zsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SZ8S1DsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SZ8S1TsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SZ8S1zsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SZ8S1jsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_AlXNgE1SEfCo_IWfKKhhfw" documentation="mensagem" name="mensagemaenviar">
            <correlation xmi:type="process:Correlation" xmi:id="_AlX0kE1SEfCo_IWfKKhhfw">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_AlX0kU1SEfCo_IWfKKhhfw"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_CWSYkE1SEfCo_IWfKKhhfw" name="Preparação de Produto" content="Preparação de Produto"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_CWU00E1SEfCo_IWfKKhhfw" name="Receber Produto" content="Receber Produto"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_AlYboU1SEfCo_IWfKKhhfw"/>
          </events>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SaRC8DsREfCFwZ2i48Dr6Q" name="Verificar se todos os componentes estão Rececionados" outgoing="_ShynQDsREfCFwZ2i48Dr6Q" incoming="_Shly8DsREfCFwZ2i48Dr6Q" actor="__ebUQE1JEfCo_IWfKKhhfw" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SaRqADsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SaRC8TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SaRqATsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_a1nzoE2yEfCeS6P5ijagaw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_a1oasE2yEfCeS6P5ijagaw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_a1pBwE2yEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_a1pBwU2yEfCeS6P5ijagaw" name="businessOrderInput.is_todos_os_componentes_rececionados" content="businessOrderInput?.is_todos_os_componentes_rececionados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_a1pBwk2yEfCeS6P5ijagaw" name="businessOrderInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_a1pBw02yEfCeS6P5ijagaw" type="JAVA_METHOD" expression="setIs_todos_os_componentes_rececionados">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SaRqAjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SaRqAzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SaRqBDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SaRqBjsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SaRqBTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SaRqCDsREfCFwZ2i48Dr6Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_cXjgcE2yEfCeS6P5ijagaw" name="todosrececionados" content="799ad297-2de0-4736-8331-b71db43b9b31" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SaRqBzsREfCFwZ2i48Dr6Q">
            <inputs xmi:type="process:ContractInput" xmi:id="_a1Wt4E2yEfCeS6P5ijagaw" name="businessOrderInput" type="COMPLEX" dataReference="businessOrder" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_a1XU8E2yEfCeS6P5ijagaw" name="is_todos_os_componentes_rececionados" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SaRqCjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_SadQMDsREfCFwZ2i48Dr6Q" name="Notificar o técnico que os produtos estão todos rececionado" outgoing="_SiZrQDsREfCFwZ2i48Dr6Q" incoming="_SiM28DsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SadQMjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SadQMTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SadQMzsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SadQNDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SadQNTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SadQNjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SadQODsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SadQNzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_Op6Z0E20EfCeS6P5ijagaw" documentation="avisartecnico" name="avisartecnico">
            <correlation xmi:type="process:Correlation" xmi:id="_Op7A4E20EfCeS6P5ijagaw">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_Op7A4U20EfCeS6P5ijagaw"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_PLeOwE20EfCeS6P5ijagaw" name="Preparação de Produto" content="Preparação de Produto"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_PLfc4E20EfCeS6P5ijagaw" name="Receber aviso do responsável de preparação" content="Receber aviso do responsável de preparação"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_Op7A5E20EfCeS6P5ijagaw"/>
          </events>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_a9VZEE1NEfCo_IWfKKhhfw" name="Verificar se é para Leiria sem cliente atribuido" outgoing="_SfuKsDsREfCFwZ2i48Dr6Q" incoming="_SfikgDsREfCFwZ2i48Dr6Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SZPvQjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SZPvQTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SZPvQzsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_rhkncE1NEfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rhkncU1NEfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rhknck1NEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rhknc01NEfCo_IWfKKhhfw" name="businessOrderInput.is_para_leiria" content="businessOrderInput?.is_para_leiria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rhkndE1NEfCo_IWfKKhhfw" name="businessOrderInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rhkndU1NEfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setIs_para_leiria">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SZPvRDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SZPvRTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SZPvRjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SZPvSDsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SZPvRzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_a9cGxE1NEfCo_IWfKKhhfw">
            <targetForm xmi:type="expression:Expression" xmi:id="_s4HjoE1NEfCo_IWfKKhhfw" name="localizacaoIslLeiria" content="779504c3-c61a-4830-90e5-1f6e9d4fbfad" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_a9cGw01NEfCo_IWfKKhhfw">
            <inputs xmi:type="process:ContractInput" xmi:id="_rha2cE1NEfCo_IWfKKhhfw" name="businessOrderInput" type="COMPLEX" dataReference="businessOrder" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_rhcEkE1NEfCo_IWfKKhhfw" name="is_para_leiria" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_a9ct0U1NEfCo_IWfKKhhfw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_llqesE3GEfCRZeFygNlKAA" name="Colocação de Etiqueta" outgoing="_DyHZwE3IEfCRZeFygNlKAA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SWyRITsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SWyRIDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SWyRIjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_B1NoME3IEfCRZeFygNlKAA" name="Verificar se o produto é para cliente ou consumo interno" outgoing="_86foYE3MEfCRZeFygNlKAA" incoming="_DyHZwE3IEfCRZeFygNlKAA" actor="__ebUQE1JEfCo_IWfKKhhfw" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_B1OPQE3IEfCRZeFygNlKAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_B1OPQU3IEfCRZeFygNlKAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_B1OPQk3IEfCRZeFygNlKAA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_yMNO0E3OEfCRZeFygNlKAA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yMNO0U3OEfCRZeFygNlKAA" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yMNO0k3OEfCRZeFygNlKAA" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yMNO003OEfCRZeFygNlKAA" name="businessOrderInput.is_consumo_interno" content="businessOrderInput?.is_consumo_interno" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yMNO1E3OEfCRZeFygNlKAA" name="businessOrderInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yMNO1U3OEfCRZeFygNlKAA" type="JAVA_METHOD" expression="setIs_consumo_interno">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_B1OQ8U3IEfCRZeFygNlKAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_B1OQ8k3IEfCRZeFygNlKAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_B1OQ803IEfCRZeFygNlKAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_B1OQ9E3IEfCRZeFygNlKAA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_B1OQ9U3IEfCRZeFygNlKAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_B1OQ9k3IEfCRZeFygNlKAA">
            <targetForm xmi:type="expression:Expression" xmi:id="_zpYXcE3OEfCRZeFygNlKAA" name="consumointerno2" content="60ecdece-14a8-48d9-ae19-799f22b82bdb" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_B1OQ-E3IEfCRZeFygNlKAA">
            <inputs xmi:type="process:ContractInput" xmi:id="_yMMAsE3OEfCRZeFygNlKAA" name="businessOrderInput" type="COMPLEX" dataReference="businessOrder" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_yMMnwE3OEfCRZeFygNlKAA" name="is_consumo_interno" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_B1OQ-U3IEfCRZeFygNlKAA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_SanBMDsREfCFwZ2i48Dr6Q" name="Assistente Lane" actor="_R2UcsE26EfCeS6P5ijagaw">
        <elements xmi:type="process:XORGateway" xmi:id="_Sbxe0DsREfCFwZ2i48Dr6Q" name="Qual o tipo de encomenfda?" outgoing="_SkkOcDsREfCFwZ2i48Dr6Q _Skt_cDsREfCFwZ2i48Dr6Q" incoming="_SkadcDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SbyF4TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SbyF4DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SbyF4jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SdrjUDsREfCFwZ2i48Dr6Q" name="Colocar a etiqueta &quot;P&quot; Verde" outgoing="_Sk3JYDsREfCFwZ2i48Dr6Q" incoming="_SkkOcDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SdsxcDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SdrjUTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SdsxcTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SdsxcjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SdsxczsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SdsxdDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SdsxdjsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SdsxdTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Sb9FADsREfCFwZ2i48Dr6Q" name="_wOLpkDsPEfC5SYqfsyMQTA" outgoing="_SlJdQDsREfCFwZ2i48Dr6Q" incoming="_Sk3JYDsREfCFwZ2i48Dr6Q _SlATUDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Sb9sETsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Sb9sEDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Sb9sEjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_F_U_AErlEfCeh5-E9Q3UIA" name="Produto Devolvido e Reencomendado" incoming="_Sj45ADsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SbX2MTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SbX2MDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SbX2MjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_SbJMsDsREfCFwZ2i48Dr6Q" name="_OiE7UDsPEfC5SYqfsyMQTA" outgoing="_SkPeUDsREfCFwZ2i48Dr6Q" incoming="_SjJSIDsREfCFwZ2i48Dr6Q _Sji6wDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SbJzwTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SbJzwDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SbJzwjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SdUW8DsREfCFwZ2i48Dr6Q" name="Devolver Produtos" outgoing="_Sj45ADsREfCFwZ2i48Dr6Q" incoming="_Sjt54DsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SdU-ATsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SdU-ADsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SdU-AjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_NlvTkE1SEfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_NlvTkU1SEfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OFMPsE1SEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_NlvTkk1SEfCo_IWfKKhhfw" name="newScript()" content="businessOrder.is_produto_devolvido = true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_W3nuoE1SEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_NlvTk01SEfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setIs_produto_devolvido">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SdU-AzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SdU-BDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SdU-BTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SdU-BzsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SdU-BjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_ScxkYDsREfCFwZ2i48Dr6Q" name="Receber aviso do responsável de preparação" outgoing="_SjJSIDsREfCFwZ2i48Dr6Q" incoming="_SiZrQDsREfCFwZ2i48Dr6Q" event="avisartecnico">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ScyLcTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ScyLcDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ScyLcjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ScyLczsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ScyLdDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ScyLdTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ScyLdzsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ScyLdjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_ScURYDsREfCFwZ2i48Dr6Q" name="Receber Produto" outgoing="_Siw3oDsREfCFwZ2i48Dr6Q" incoming="_pI6moE1QEfCo_IWfKKhhfw" event="mensagemaenviar">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ScU4cTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ScU4cDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ScU4cjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ScU4czsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ScU4dDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ScU4dTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ScU4dzsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ScU4djsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PKIT8E1REfCo_IWfKKhhfw" name="Validar com as imagens  se  a Embalagem está danificada" outgoing="_Si9r8DsREfCFwZ2i48Dr6Q" incoming="_Siw3oDsREfCFwZ2i48Dr6Q" actor="_R2UcsE26EfCeS6P5ijagaw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Sc-YsTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Sc-YsDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Sc-YsjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_cfbhIE1REfCo_IWfKKhhfw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cfbhIU1REfCo_IWfKKhhfw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cfbhIk1REfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cfcIME1REfCo_IWfKKhhfw" name="businessOrderInput.is_danificada" content="businessOrderInput?.is_danificada" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cfcIMU1REfCo_IWfKKhhfw" name="businessOrderInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cfcIMk1REfCo_IWfKKhhfw" type="JAVA_METHOD" expression="setIs_danificada">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Sc-YszsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Sc-YtDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Sc-YtTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Sc-YtzsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Sc-YtjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PKQ2001REfCo_IWfKKhhfw">
            <targetForm xmi:type="expression:Expression" xmi:id="_dxC6AE1REfCo_IWfKKhhfw" name="newForm11" content="ad30775c-3d59-49ae-be4c-b56880117fdc" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PKQ20k1REfCo_IWfKKhhfw">
            <inputs xmi:type="process:ContractInput" xmi:id="_cfS-QE1REfCo_IWfKKhhfw" name="businessOrderInput" type="COMPLEX" dataReference="businessOrder" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_cfUzcE1REfCo_IWfKKhhfw" name="is_danificada" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PKRd4E1REfCo_IWfKKhhfw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_HB_V4ErlEfCeh5-E9Q3UIA" name="Produto pronto para entrega" incoming="_SlJdQDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ScG2AjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ScG2ATsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ScG2AzsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SdJX0DsREfCFwZ2i48Dr6Q" name="Embalar e preparar produto na caixa da encomenda" outgoing="_Sji6wDsREfCFwZ2i48Dr6Q" incoming="_SjVfYDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SdJ-4TsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SdJ-4DsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SdJ-4jsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_PVsXME2zEfCeS6P5ijagaw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PVtlUE2zEfCeS6P5ijagaw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pw5FcE2zEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PVuMYE2zEfCeS6P5ijagaw" name="newScript()" content="businessOrder.is_produto_preparado = true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_U6vUIE2zEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PVuMYU2zEfCeS6P5ijagaw" type="JAVA_METHOD" expression="setIs_produto_preparado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SdJ-4zsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SdJ-5DsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SdJ-5TsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SdJ-5zsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SdJ-5jsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Sa6jMDsREfCFwZ2i48Dr6Q" name="Produto Danificado?" outgoing="_SjVfYDsREfCFwZ2i48Dr6Q _Sjt54DsREfCFwZ2i48Dr6Q" incoming="_Si9r8DsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Sa7KQTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Sa7KQDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Sa7KQjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Sd17YDsREfCFwZ2i48Dr6Q" name="Adicionar informação do cliente e Colocar a etiqueta &quot;P&quot;" outgoing="_SlATUDsREfCFwZ2i48Dr6Q" incoming="_Skt_cDsREfCFwZ2i48Dr6Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Sd2icTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Sd2icDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Sd2icjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Sd2iczsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Sd2idDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Sd2idTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Sd2idzsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Sd2idjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_WvoZME2zEfCeS6P5ijagaw" name="Verificar o tipo de encomenda" outgoing="_SkadcDsREfCFwZ2i48Dr6Q" incoming="_SkPeUDsREfCFwZ2i48Dr6Q" actor="_R2UcsE26EfCeS6P5ijagaw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SdgkMTsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SdgkMDsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SdgkMjsREfCFwZ2i48Dr6Q" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_lZEHwE2zEfCeS6P5ijagaw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_lZEHwU2zEfCeS6P5ijagaw" name="businessOrder" content="businessOrder" type="TYPE_VARIABLE" returnType="com.company.model.BusinessOrder">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_lZEu0E2zEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_lZEu0U2zEfCeS6P5ijagaw" name="businessOrderInput.tipo_encomenda" content="businessOrderInput?.tipo_encomenda" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_lZEu0k2zEfCeS6P5ijagaw" name="businessOrderInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_lZEu002zEfCeS6P5ijagaw" type="JAVA_METHOD" expression="setTipo_encomenda">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SdgkMzsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SdgkNDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SdgkNTsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SdgkNzsREfCFwZ2i48Dr6Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SdgkNjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_WwQESE2zEfCeS6P5ijagaw">
            <targetForm xmi:type="expression:Expression" xmi:id="_mwjfIE2zEfCeS6P5ijagaw" name="tipoencomenda" content="a1caf425-0719-4bfe-8d40-028cb1476b51" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_WwQER02zEfCeS6P5ijagaw">
            <inputs xmi:type="process:ContractInput" xmi:id="_lZBEcE2zEfCeS6P5ijagaw" name="businessOrderInput" type="COMPLEX" dataReference="businessOrder" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_lZBrgE2zEfCeS6P5ijagaw" name="tipo_encomenda" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_WwQrUU2zEfCeS6P5ijagaw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_SHY-AE1LEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder">
        <defaultValue xmi:type="expression:Expression" xmi:id="_SHZlEE1LEfCo_IWfKKhhfw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Sq0B4E1QEfCo_IWfKKhhfw" name="mensagem" dataType="_SPbr9TsREfCFwZ2i48Dr6Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Sq0o8E1QEfCo_IWfKKhhfw" name="" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_ZKnW4E1QEfCo_IWfKKhhfw" name="variavel" dataType="_SPbr9TsREfCFwZ2i48Dr6Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ZKn98E1QEfCo_IWfKKhhfw" name="Receção do Produto para Aprovisionamento" content="Receção do Produto para Aprovisionamento"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_SVc0YDsREfCFwZ2i48Dr6Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_cg9N4E3PEfCRZeFygNlKAA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_SVc0YjsREfCFwZ2i48Dr6Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_SVc0YzsREfCFwZ2i48Dr6Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SfBnIDsREfCFwZ2i48Dr6Q" name="Cliente" target="_SZBs0DsREfCFwZ2i48Dr6Q" source="_SX1aADsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SfBnITsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SfBnIjsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_consumo_interno == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_-IyVkE3OEfCRZeFygNlKAA" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SfQ3sDsREfCFwZ2i48Dr6Q" name="Consumo Interno" target="_SZIagDsREfCFwZ2i48Dr6Q" source="_SX1aADsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SfQ3sTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SfRewDsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_consumo_interno == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__sj1cE3OEfCRZeFygNlKAA" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SfikgDsREfCFwZ2i48Dr6Q" target="_a9VZEE1NEfCo_IWfKKhhfw" source="_SZIagDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SfikgTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SfikgjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SfuKsDsREfCFwZ2i48Dr6Q" target="_SYEDgDsREfCFwZ2i48Dr6Q" source="_a9VZEE1NEfCo_IWfKKhhfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SfuKsTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SfuKsjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sf5w4DsREfCFwZ2i48Dr6Q" name="Sim" target="_SZZgQDsREfCFwZ2i48Dr6Q" source="_SYEDgDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sf5w4TsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sf5w4jsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_para_leiria==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FfWYEE1OEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SgEI8DsREfCFwZ2i48Dr6Q" name="Não" target="_SZj4UDsREfCFwZ2i48Dr6Q" source="_SYEDgDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SgEwADsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SgEwATsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_para_leiria==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HFZI0E1OEfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SgPIEDsREfCFwZ2i48Dr6Q" target="_SYRe4DsREfCFwZ2i48Dr6Q" source="_SZZgQDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SgPIETsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SgPIEjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SgauQDsREfCFwZ2i48Dr6Q" target="_SYRe4DsREfCFwZ2i48Dr6Q" source="_SZj4UDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SgauQTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SgauQjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sgm7gDsREfCFwZ2i48Dr6Q" target="_SYbP4DsREfCFwZ2i48Dr6Q" source="_SYRe4DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SgnikDsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SgnikTsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SgyhsDsREfCFwZ2i48Dr6Q" target="_SYbP4DsREfCFwZ2i48Dr6Q" source="_SZBs0DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SgyhsTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SgzIwDsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sg_WADsREfCFwZ2i48Dr6Q" target="_SZu3cDsREfCFwZ2i48Dr6Q" source="_SYbP4DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sg_WATsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sg_WAjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Shly8DsREfCFwZ2i48Dr6Q" target="_SaRC8DsREfCFwZ2i48Dr6Q" source="_SYkZ0DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Shly8TsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Shly8jsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ShynQDsREfCFwZ2i48Dr6Q" target="_SY370DsREfCFwZ2i48Dr6Q" source="_SaRC8DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ShynQTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_ShynQjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sh-0gDsREfCFwZ2i48Dr6Q" name="Não" target="_SX1aADsREfCFwZ2i48Dr6Q" source="_SY370DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sh-0gTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sh-0gjsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_todos_os_componentes_rececionados==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qqCHkE2yEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SiM28DsREfCFwZ2i48Dr6Q" name="Sim" target="_SadQMDsREfCFwZ2i48Dr6Q" source="_SY370DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SiNeADsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SiNeATsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_todos_os_componentes_rececionados==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_sh7dUE2yEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SiZrQDsREfCFwZ2i48Dr6Q" target="_ScxkYDsREfCFwZ2i48Dr6Q" source="_SadQMDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SiZrQTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SiaSUDsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Siw3oDsREfCFwZ2i48Dr6Q" target="_PKIT8E1REfCo_IWfKKhhfw" source="_ScURYDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SixesDsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SixesTsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Si9r8DsREfCFwZ2i48Dr6Q" target="_Sa6jMDsREfCFwZ2i48Dr6Q" source="_PKIT8E1REfCo_IWfKKhhfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Si9r8TsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Si9r8jsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SjJSIDsREfCFwZ2i48Dr6Q" target="_SbJMsDsREfCFwZ2i48Dr6Q" source="_ScxkYDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SjJ5MDsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SjJ5MTsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SjVfYDsREfCFwZ2i48Dr6Q" name="Não" target="_SdJX0DsREfCFwZ2i48Dr6Q" source="_Sa6jMDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SjWGcDsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SjWGcTsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_danificada==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pz7dEE1REfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sji6wDsREfCFwZ2i48Dr6Q" target="_SbJMsDsREfCFwZ2i48Dr6Q" source="_SdJX0DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sji6wTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sji6wjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sjt54DsREfCFwZ2i48Dr6Q" name="Sim" target="_SdUW8DsREfCFwZ2i48Dr6Q" source="_Sa6jMDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sjt54TsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sjt54jsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.is_danificada==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rTsmsE1REfCo_IWfKKhhfw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sj45ADsREfCFwZ2i48Dr6Q" target="_F_U_AErlEfCeh5-E9Q3UIA" source="_SdUW8DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sj45ATsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sj45AjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SkPeUDsREfCFwZ2i48Dr6Q" target="_WvoZME2zEfCeS6P5ijagaw" source="_SbJMsDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SkPeUTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SkPeUjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SkadcDsREfCFwZ2i48Dr6Q" target="_Sbxe0DsREfCFwZ2i48Dr6Q" source="_WvoZME2zEfCeS6P5ijagaw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SkadcTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SkadcjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SkkOcDsREfCFwZ2i48Dr6Q" name="Tipo P" target="_SdrjUDsREfCFwZ2i48Dr6Q" source="_Sbxe0DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SkkOcTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SkkOcjsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.tipo_encomenda == &quot;P&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1cfIEE2zEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Skt_cDsREfCFwZ2i48Dr6Q" name="Tipo S" target="_Sd17YDsREfCFwZ2i48Dr6Q" source="_Sbxe0DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Skt_cTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Skt_cjsREfCFwZ2i48Dr6Q" name="newScript()" content="businessOrder.tipo_encomenda == &quot;S&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_29mVgE2zEfCeS6P5ijagaw" name="businessOrder" dataType="_SPbr-DsREfCFwZ2i48Dr6Q" className="com.company.model.BusinessOrder"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sk3JYDsREfCFwZ2i48Dr6Q" target="_Sb9FADsREfCFwZ2i48Dr6Q" source="_SdrjUDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sk3JYTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sk3JYjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SlATUDsREfCFwZ2i48Dr6Q" target="_Sb9FADsREfCFwZ2i48Dr6Q" source="_Sd17YDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SlATUTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SlATUjsREfCFwZ2i48Dr6Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SlJdQDsREfCFwZ2i48Dr6Q" target="_HB_V4ErlEfCeh5-E9Q3UIA" source="_Sb9FADsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SlJdQTsREfCFwZ2i48Dr6Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_SlJdQjsREfCFwZ2i48Dr6Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nQvkEE1QEfCo_IWfKKhhfw" target="_SYkZ0DsREfCFwZ2i48Dr6Q" source="_SZu3cDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nQ4uAE1QEfCo_IWfKKhhfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_nQ5VEE1QEfCo_IWfKKhhfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_odJs0E1QEfCo_IWfKKhhfw" target="_SZ7rwDsREfCFwZ2i48Dr6Q" source="_SYkZ0DsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_odS2wE1QEfCo_IWfKKhhfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_odUE4E1QEfCo_IWfKKhhfw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pI6moE1QEfCo_IWfKKhhfw" target="_ScURYDsREfCFwZ2i48Dr6Q" source="_SZ7rwDsREfCFwZ2i48Dr6Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pI8b0E1QEfCo_IWfKKhhfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_pI8b0U1QEfCo_IWfKKhhfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DyHZwE3IEfCRZeFygNlKAA" target="_B1NoME3IEfCRZeFygNlKAA" source="_llqesE3GEfCRZeFygNlKAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DyM5UE3IEfCRZeFygNlKAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_DyNgYE3IEfCRZeFygNlKAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_86foYE3MEfCRZeFygNlKAA" target="_SX1aADsREfCFwZ2i48Dr6Q" source="_B1NoME3IEfCRZeFygNlKAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_86j50E3MEfCRZeFygNlKAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_86kg4E3MEfCRZeFygNlKAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="__ebUQE1JEfCo_IWfKKhhfw" name="Responsável Lane" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_R2UcsE26EfCeS6P5ijagaw" name="Assistente Lane"/>
      <contract xmi:type="process:Contract" xmi:id="_SVc0ZDsREfCFwZ2i48Dr6Q"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SVZxEDsREfCFwZ2i48Dr6Q">
        <name xmi:type="expression:Expression" xmi:id="_SVZxETsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SVZxEjsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SVZxEzsREfCFwZ2i48Dr6Q">
        <name xmi:type="expression:Expression" xmi:id="_SVZxFDsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SVZxFTsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SVZxFjsREfCFwZ2i48Dr6Q">
        <name xmi:type="expression:Expression" xmi:id="_SVZxFzsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SVZxGDsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SVZxGTsREfCFwZ2i48Dr6Q">
        <name xmi:type="expression:Expression" xmi:id="_SVZxGjsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SVZxGzsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SVZxHDsREfCFwZ2i48Dr6Q">
        <name xmi:type="expression:Expression" xmi:id="_SVZxHTsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SVZxHjsREfCFwZ2i48Dr6Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_SPbr8DsREfCFwZ2i48Dr6Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_SPbr8TsREfCFwZ2i48Dr6Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_SPbr8jsREfCFwZ2i48Dr6Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_SPbr8zsREfCFwZ2i48Dr6Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_SPbr9DsREfCFwZ2i48Dr6Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_SPbr9TsREfCFwZ2i48Dr6Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_SPbr9jsREfCFwZ2i48Dr6Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_SPbr9zsREfCFwZ2i48Dr6Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_SPbr-DsREfCFwZ2i48Dr6Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_SPVlUDsREfCFwZ2i48Dr6Q" type="Process" element="_SPTwIDsREfCFwZ2i48Dr6Q" name="Prepracaodeproduto - 1.0" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_SVmlYDsREfCFwZ2i48Dr6Q" type="2007" element="_SRhWoDsREfCFwZ2i48Dr6Q">
      <children xmi:type="notation:DecorationNode" xmi:id="_SVnMcDsREfCFwZ2i48Dr6Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_SVnMcTsREfCFwZ2i48Dr6Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_SWOQcDsREfCFwZ2i48Dr6Q" type="3007" element="_SWNCUDsREfCFwZ2i48Dr6Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_SWO3gDsREfCFwZ2i48Dr6Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_SWPekDsREfCFwZ2i48Dr6Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_SX2oIDsREfCFwZ2i48Dr6Q" type="3008" element="_SX1aADsREfCFwZ2i48Dr6Q" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_SX3PMDsREfCFwZ2i48Dr6Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SX3PMTsREfCFwZ2i48Dr6Q" y="-66"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SX2oITsREfCFwZ2i48Dr6Q" x="513" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SYF4sDsREfCFwZ2i48Dr6Q" type="3008" element="_SYEDgDsREfCFwZ2i48Dr6Q" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_SYF4sjsREfCFwZ2i48Dr6Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SYF4szsREfCFwZ2i48Dr6Q" x="-112" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SYF4sTsREfCFwZ2i48Dr6Q" x="989" y="193"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SYTUEDsREfCFwZ2i48Dr6Q" type="3008" element="_SYRe4DsREfCFwZ2i48Dr6Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SYTUEjsREfCFwZ2i48Dr6Q" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SYTUEzsREfCFwZ2i48Dr6Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SYTUETsREfCFwZ2i48Dr6Q" x="1269" y="193"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SYceADsREfCFwZ2i48Dr6Q" type="3008" element="_SYbP4DsREfCFwZ2i48Dr6Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SYceAjsREfCFwZ2i48Dr6Q" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SYceAzsREfCFwZ2i48Dr6Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SYceATsREfCFwZ2i48Dr6Q" x="1360" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SYmPADsREfCFwZ2i48Dr6Q" type="3009" element="_SYkZ0DsREfCFwZ2i48Dr6Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SYmPAjsREfCFwZ2i48Dr6Q" visible="false" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SYmPAzsREfCFwZ2i48Dr6Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SYmPATsREfCFwZ2i48Dr6Q" x="1857" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SY5J8DsREfCFwZ2i48Dr6Q" type="3008" element="_SY370DsREfCFwZ2i48Dr6Q" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_SY5J8jsREfCFwZ2i48Dr6Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SY5J8zsREfCFwZ2i48Dr6Q" x="-127" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SY5J8TsREfCFwZ2i48Dr6Q" x="2179" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SZC68DsREfCFwZ2i48Dr6Q" type="3027" element="_SZBs0DsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SZDiADsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SZC68TsREfCFwZ2i48Dr6Q" x="637" y="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SZJBkDsREfCFwZ2i48Dr6Q" type="3027" element="_SZIagDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SZJBkjsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SZJBkTsREfCFwZ2i48Dr6Q" x="612" y="185"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SZauYDsREfCFwZ2i48Dr6Q" type="3027" element="_SZZgQDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SZauYjsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SZauYTsREfCFwZ2i48Dr6Q" x="1139" y="149"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SZltgDsREfCFwZ2i48Dr6Q" type="3027" element="_SZj4UDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SZltgjsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SZltgTsREfCFwZ2i48Dr6Q" x="1139" y="250"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SZxTsDsREfCFwZ2i48Dr6Q" type="3005" element="_SZu3cDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SZxTsjsREfCFwZ2i48Dr6Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SZxTsTsREfCFwZ2i48Dr6Q" x="1450" y="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SZ-IADsREfCFwZ2i48Dr6Q" type="3025" element="_SZ7rwDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SZ-IAjsREfCFwZ2i48Dr6Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SZ-IATsREfCFwZ2i48Dr6Q" x="1829" y="264" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SaS4IDsREfCFwZ2i48Dr6Q" type="3005" element="_SaRC8DsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SaS4IjsREfCFwZ2i48Dr6Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SaS4ITsREfCFwZ2i48Dr6Q" x="1941" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SaeeUDsREfCFwZ2i48Dr6Q" type="3025" element="_SadQMDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SafFYDsREfCFwZ2i48Dr6Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SaeeUTsREfCFwZ2i48Dr6Q" x="2527" y="77" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_a9hmUE1NEfCo_IWfKKhhfw" type="3005" element="_a9VZEE1NEfCo_IWfKKhhfw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_a9l3wE1NEfCo_IWfKKhhfw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_a9hmUU1NEfCo_IWfKKhhfw" x="821" y="185" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lmF8gE3GEfCRZeFygNlKAA" type="3002" element="_llqesE3GEfCRZeFygNlKAA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_lmPGcE3GEfCRZeFygNlKAA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_lmPtgE3GEfCRZeFygNlKAA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lmHxsE3GEfCRZeFygNlKAA" x="108" y="78" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B1WyIE3IEfCRZeFygNlKAA" type="3005" element="_B1NoME3IEfCRZeFygNlKAA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_B1WyIU3IEfCRZeFygNlKAA" type="5005" element="_B1NoME3IEfCRZeFygNlKAA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B1WyIk3IEfCRZeFygNlKAA" x="189" y="60" width="160" height="80"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_SWOQcTsREfCFwZ2i48Dr6Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_SWOQcjsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_SWOQczsREfCFwZ2i48Dr6Q" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_SWPekTsREfCFwZ2i48Dr6Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SWOQdDsREfCFwZ2i48Dr6Q" x="48" y="10" width="3762" height="850"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_SanoQDsREfCFwZ2i48Dr6Q" type="3007" element="_SanBMDsREfCFwZ2i48Dr6Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_SaoPUTsREfCFwZ2i48Dr6Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_SaoPUjsREfCFwZ2i48Dr6Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_SbzUADsREfCFwZ2i48Dr6Q" type="3008" element="_Sbxe0DsREfCFwZ2i48Dr6Q" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_SbzUAjsREfCFwZ2i48Dr6Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SbzUAzsREfCFwZ2i48Dr6Q" x="-75" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SbzUATsREfCFwZ2i48Dr6Q" x="2850" y="157"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SdtYgDsREfCFwZ2i48Dr6Q" type="3027" element="_SdrjUDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SdtYgjsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SdtYgTsREfCFwZ2i48Dr6Q" x="2990" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sb_hQDsREfCFwZ2i48Dr6Q" type="3008" element="_Sb9FADsREfCFwZ2i48Dr6Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sb_hQjsREfCFwZ2i48Dr6Q" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Sb_hQzsREfCFwZ2i48Dr6Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sb_hQTsREfCFwZ2i48Dr6Q" x="3200" y="157"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F_glMErlEfCeh5-E9Q3UIA" type="3003" element="_F_U_AErlEfCeh5-E9Q3UIA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F_hMQErlEfCeh5-E9Q3UIA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F_hMQUrlEfCeh5-E9Q3UIA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F_glMUrlEfCeh5-E9Q3UIA" x="3395" y="310" width="29" height="29"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SbLB4DsREfCFwZ2i48Dr6Q" type="3009" element="_SbJMsDsREfCFwZ2i48Dr6Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SbLo8DsREfCFwZ2i48Dr6Q" visible="false" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SbLo8TsREfCFwZ2i48Dr6Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SbLB4TsREfCFwZ2i48Dr6Q" x="2584" y="163"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SdWMIDsREfCFwZ2i48Dr6Q" type="3027" element="_SdUW8DsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SdWMIjsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SdWMITsREfCFwZ2i48Dr6Q" x="2331" y="310"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ScyygDsREfCFwZ2i48Dr6Q" type="3026" element="_ScxkYDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SczZkDsREfCFwZ2i48Dr6Q" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ScyygTsREfCFwZ2i48Dr6Q" x="2555" y="17"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ScWtoDsREfCFwZ2i48Dr6Q" type="3026" element="_ScURYDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ScXUsDsREfCFwZ2i48Dr6Q" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ScWtoTsREfCFwZ2i48Dr6Q" x="1852" y="150"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PKbO4E1REfCo_IWfKKhhfw" type="3005" element="_PKIT8E1REfCo_IWfKKhhfw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PKe5QE1REfCo_IWfKKhhfw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PKbO4U1REfCo_IWfKKhhfw" x="1995" y="150" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HB_V5ErlEfCeh5-E9Q3UIA" type="3003" element="_HB_V4ErlEfCeh5-E9Q3UIA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HB_V5krlEfCeh5-E9Q3UIA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HB_V50rlEfCeh5-E9Q3UIA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HB_V5UrlEfCeh5-E9Q3UIA" x="3397" y="162" width="29" height="29"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SdLNADsREfCFwZ2i48Dr6Q" type="3027" element="_SdJX0DsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SdL0EDsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SdLNATsREfCFwZ2i48Dr6Q" x="2286" y="149"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sa8YYDsREfCFwZ2i48Dr6Q" type="3008" element="_Sa6jMDsREfCFwZ2i48Dr6Q" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sa8_cDsREfCFwZ2i48Dr6Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Sa8_cTsREfCFwZ2i48Dr6Q" x="-43" y="-66"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sa8YYTsREfCFwZ2i48Dr6Q" x="2178" y="157"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sd3wkDsREfCFwZ2i48Dr6Q" type="3027" element="_Sd17YDsREfCFwZ2i48Dr6Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sd3wkjsREfCFwZ2i48Dr6Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sd3wkTsREfCFwZ2i48Dr6Q" x="2990" y="215"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WwkNUE2zEfCeS6P5ijagaw" type="3005" element="_WvoZME2zEfCeS6P5ijagaw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WwriEE2zEfCeS6P5ijagaw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Wwk0YE2zEfCeS6P5ijagaw" x="2680" y="153" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_SanoQTsREfCFwZ2i48Dr6Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_SanoQjsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_SanoQzsREfCFwZ2i48Dr6Q" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_SapdcDsREfCFwZ2i48Dr6Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SaoPUDsREfCFwZ2i48Dr6Q" x="23" y="550" width="3762" height="400"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_SVmlYTsREfCFwZ2i48Dr6Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_SVmlYjsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_SVmlYzsREfCFwZ2i48Dr6Q" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_SVnMcjsREfCFwZ2i48Dr6Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SVmlZDsREfCFwZ2i48Dr6Q" width="3785" height="865"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_SPVlUTsREfCFwZ2i48Dr6Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_SfCOMDsREfCFwZ2i48Dr6Q" type="4001" element="_SfBnIDsREfCFwZ2i48Dr6Q" source="_SX2oIDsREfCFwZ2i48Dr6Q" target="_SZC68DsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SfC1QjsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SfC1QzsREfCFwZ2i48Dr6Q" x="-20" y="17"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SfC1QDsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SfC1QTsREfCFwZ2i48Dr6Q" points="[0, 0, -83, 0]$[83, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SfT7ADsREfCFwZ2i48Dr6Q" type="4001" element="_SfQ3sDsREfCFwZ2i48Dr6Q" source="_SX2oIDsREfCFwZ2i48Dr6Q" target="_SZJBkDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SfT7AzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SfT7BDsREfCFwZ2i48Dr6Q" x="1" y="50"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SfT7ATsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SfT7AjsREfCFwZ2i48Dr6Q" points="[0, 0, -77, -109]$[0, 109, -77, 0]$[77, 109, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SfjLkDsREfCFwZ2i48Dr6Q" type="4001" element="_SfikgDsREfCFwZ2i48Dr6Q" source="_SZJBkDsREfCFwZ2i48Dr6Q" target="_a9hmUE1NEfCo_IWfKKhhfw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SfjLkzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SfjLlDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SfjLkTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SfjLkjsREfCFwZ2i48Dr6Q" points="[0, 0, -35, 0]$[35, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SfuKszsREfCFwZ2i48Dr6Q" type="4001" element="_SfuKsDsREfCFwZ2i48Dr6Q" source="_a9hmUE1NEfCo_IWfKKhhfw" target="_SYF4sDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SfuxwDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SfuxwTsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SfuKtDsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SfuKtTsREfCFwZ2i48Dr6Q" points="[0, 0, -51, 0]$[51, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sf6X8DsREfCFwZ2i48Dr6Q" type="4001" element="_Sf5w4DsREfCFwZ2i48Dr6Q" source="_SYF4sDsREfCFwZ2i48Dr6Q" target="_SZauYDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sf6X8zsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sf6X9DsREfCFwZ2i48Dr6Q" x="-11" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sf6X8TsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sf6X8jsREfCFwZ2i48Dr6Q" points="[0, 0, -122, 28]$[0, -28, -122, 0]$[122, -28, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SgFXEDsREfCFwZ2i48Dr6Q" type="4001" element="_SgEI8DsREfCFwZ2i48Dr6Q" source="_SYF4sDsREfCFwZ2i48Dr6Q" target="_SZltgDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SgFXEzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SgFXFDsREfCFwZ2i48Dr6Q" x="-12" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SgFXETsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SgFXEjsREfCFwZ2i48Dr6Q" points="[0, 0, -130, -44]$[0, 44, -130, 0]$[130, 44, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SgPvIDsREfCFwZ2i48Dr6Q" type="4001" element="_SgPIEDsREfCFwZ2i48Dr6Q" source="_SZauYDsREfCFwZ2i48Dr6Q" target="_SYTUEDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SgQWMDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SgQWMTsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SgPvITsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SgPvIjsREfCFwZ2i48Dr6Q" points="[0, 0, -50, -21]$[50, 0, 0, -21]$[50, 21, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SgbVUDsREfCFwZ2i48Dr6Q" type="4001" element="_SgauQDsREfCFwZ2i48Dr6Q" source="_SZltgDsREfCFwZ2i48Dr6Q" target="_SYTUEDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sgb8YDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sgb8YTsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SgbVUTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SgbVUjsREfCFwZ2i48Dr6Q" points="[0, 0, -49, 44]$[49, 0, 0, 44]$[49, -44, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SgoJoDsREfCFwZ2i48Dr6Q" type="4001" element="_Sgm7gDsREfCFwZ2i48Dr6Q" source="_SYTUEDsREfCFwZ2i48Dr6Q" target="_SYceADsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SgowsDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SgowsTsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SgoJoTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SgoJojsREfCFwZ2i48Dr6Q" points="[0, 0, -68, 95]$[68, 0, 0, 95]$[68, -95, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SgzIwTsREfCFwZ2i48Dr6Q" type="4001" element="_SgyhsDsREfCFwZ2i48Dr6Q" source="_SZC68DsREfCFwZ2i48Dr6Q" target="_SYceADsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SgzIxDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SgzIxTsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SgzIwjsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SgzIwzsREfCFwZ2i48Dr6Q" points="[0, 0, -625, 0]$[625, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sg_9EDsREfCFwZ2i48Dr6Q" type="4001" element="_Sg_WADsREfCFwZ2i48Dr6Q" source="_SYceADsREfCFwZ2i48Dr6Q" target="_SZxTsDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sg_9EzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sg_9FDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sg_9ETsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sg_9EjsREfCFwZ2i48Dr6Q" points="[0, 0, -53, 0]$[53, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ShnBEDsREfCFwZ2i48Dr6Q" type="4001" element="_Shly8DsREfCFwZ2i48Dr6Q" source="_SYmPADsREfCFwZ2i48Dr6Q" target="_SaS4IDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_ShnBEzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ShnBFDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ShnBETsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ShnBEjsREfCFwZ2i48Dr6Q" points="[0, 0, -41, 0]$[41, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Shz1YDsREfCFwZ2i48Dr6Q" type="4001" element="_ShynQDsREfCFwZ2i48Dr6Q" source="_SaS4IDsREfCFwZ2i48Dr6Q" target="_SY5J8DsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Shz1YzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Shz1ZDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Shz1YTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Shz1YjsREfCFwZ2i48Dr6Q" points="[0, 0, -97, 0]$[97, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SiACoDsREfCFwZ2i48Dr6Q" type="4001" element="_Sh-0gDsREfCFwZ2i48Dr6Q" source="_SY5J8DsREfCFwZ2i48Dr6Q" target="_SX2oIDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SiACozsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SiACpDsREfCFwZ2i48Dr6Q" x="10" y="-2"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SiACoTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SiACojsREfCFwZ2i48Dr6Q" points="[9, -13, 1817, -11]$[9, -71, 1817, -69]$[-1801, -71, 7, -69]$[-1801, -17, 7, -15]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8COjoE3MEfCRZeFygNlKAA" id="(0.5348837209302325,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SiOsIDsREfCFwZ2i48Dr6Q" type="4001" element="_SiM28DsREfCFwZ2i48Dr6Q" source="_SY5J8DsREfCFwZ2i48Dr6Q" target="_SaeeUDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SiOsIzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SiOsJDsREfCFwZ2i48Dr6Q" x="-11" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SiOsITsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SiOsIjsREfCFwZ2i48Dr6Q" points="[0, 0, -112, 0]$[112, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SiaSUTsREfCFwZ2i48Dr6Q" type="4001" element="_SiZrQDsREfCFwZ2i48Dr6Q" source="_SaeeUDsREfCFwZ2i48Dr6Q" target="_ScyygDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SibgcjsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SibgczsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SibgcDsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SibgcTsREfCFwZ2i48Dr6Q" points="[50, 0, -185, -398]$[233, 0, -2, -398]$[233, 373, -2, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SiyFwDsREfCFwZ2i48Dr6Q" type="4001" element="_Siw3oDsREfCFwZ2i48Dr6Q" source="_ScWtoDsREfCFwZ2i48Dr6Q" target="_PKbO4E1REfCo_IWfKKhhfw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Siys0DsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Siys0TsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SiyFwTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SiyFwjsREfCFwZ2i48Dr6Q" points="[0, 0, -69, 0]$[69, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Si-TADsREfCFwZ2i48Dr6Q" type="4001" element="_Si9r8DsREfCFwZ2i48Dr6Q" source="_PKbO4E1REfCo_IWfKKhhfw" target="_Sa8YYDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Si-6EDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Si-6ETsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Si-TATsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Si-TAjsREfCFwZ2i48Dr6Q" points="[0, 0, -59, 0]$[59, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SjJ5MjsREfCFwZ2i48Dr6Q" type="4001" element="_SjJSIDsREfCFwZ2i48Dr6Q" source="_ScyygDsREfCFwZ2i48Dr6Q" target="_SbLB4DsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SjKgQDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SjKgQTsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SjJ5MzsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SjJ5NDsREfCFwZ2i48Dr6Q" points="[0, 0, 0, -77]$[0, 77, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SjWtgDsREfCFwZ2i48Dr6Q" type="4001" element="_SjVfYDsREfCFwZ2i48Dr6Q" source="_Sa8YYDsREfCFwZ2i48Dr6Q" target="_SdLNADsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SjWtgzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SjWthDsREfCFwZ2i48Dr6Q" x="-11" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SjWtgTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SjWtgjsREfCFwZ2i48Dr6Q" points="[0, 0, -69, 0]$[69, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sjjh0DsREfCFwZ2i48Dr6Q" type="4001" element="_Sji6wDsREfCFwZ2i48Dr6Q" source="_SdLNADsREfCFwZ2i48Dr6Q" target="_SbLB4DsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sjjh0zsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sjjh1DsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sjjh0TsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sjjh0jsREfCFwZ2i48Dr6Q" points="[0, 0, -150, 0]$[150, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sjug8DsREfCFwZ2i48Dr6Q" type="4001" element="_Sjt54DsREfCFwZ2i48Dr6Q" source="_Sa8YYDsREfCFwZ2i48Dr6Q" target="_SdWMIDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SjvIADsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SjvIATsREfCFwZ2i48Dr6Q" x="-108" y="-19"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sjug8TsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sjug8jsREfCFwZ2i48Dr6Q" points="[3, 19, -179, -138]$[3, 156, -179, -1]$[132, 156, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sj5gEDsREfCFwZ2i48Dr6Q" type="4001" element="_Sj45ADsREfCFwZ2i48Dr6Q" source="_SdWMIDsREfCFwZ2i48Dr6Q" target="_F_glMErlEfCeh5-E9Q3UIA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sj5gEzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sj5gFDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sj5gETsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sj5gEjsREfCFwZ2i48Dr6Q" points="[0, 0, -937, 0]$[937, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SkQFYDsREfCFwZ2i48Dr6Q" type="4001" element="_SkPeUDsREfCFwZ2i48Dr6Q" source="_SbLB4DsREfCFwZ2i48Dr6Q" target="_WwkNUE2zEfCeS6P5ijagaw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SkQFYzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SkQFZDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SkQFYTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SkQFYjsREfCFwZ2i48Dr6Q" points="[0, 0, -55, 0]$[55, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SkadczsREfCFwZ2i48Dr6Q" type="4001" element="_SkadcDsREfCFwZ2i48Dr6Q" source="_WwkNUE2zEfCeS6P5ijagaw" target="_SbzUADsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SkbrkDsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SkbrkTsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SkaddDsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SkaddTsREfCFwZ2i48Dr6Q" points="[0, 0, -46, 0]$[46, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SklckDsREfCFwZ2i48Dr6Q" type="4001" element="_SkkOcDsREfCFwZ2i48Dr6Q" source="_SbzUADsREfCFwZ2i48Dr6Q" target="_SdtYgDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SklckzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SkmDoDsREfCFwZ2i48Dr6Q" x="-22" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SklckTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SklckjsREfCFwZ2i48Dr6Q" points="[0, 0, -119, 60]$[0, -60, -119, 0]$[119, -60, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SkvNkDsREfCFwZ2i48Dr6Q" type="4001" element="_Skt_cDsREfCFwZ2i48Dr6Q" source="_SbzUADsREfCFwZ2i48Dr6Q" target="_Sd3wkDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SkvNkzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SkvNlDsREfCFwZ2i48Dr6Q" x="-22" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SkvNkTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SkvNkjsREfCFwZ2i48Dr6Q" points="[0, 0, -120, -43]$[0, 43, -120, 0]$[120, 43, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sk3wcDsREfCFwZ2i48Dr6Q" type="4001" element="_Sk3JYDsREfCFwZ2i48Dr6Q" source="_SdtYgDsREfCFwZ2i48Dr6Q" target="_Sb_hQDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sk3wczsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sk3wdDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sk3wcTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sk3wcjsREfCFwZ2i48Dr6Q" points="[50, 11, -131, -56]$[181, 11, 0, -56]$[181, 46, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SlA6YDsREfCFwZ2i48Dr6Q" type="4001" element="_SlATUDsREfCFwZ2i48Dr6Q" source="_Sd3wkDsREfCFwZ2i48Dr6Q" target="_Sb_hQDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SlA6YzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SlA6ZDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SlA6YTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SlA6YjsREfCFwZ2i48Dr6Q" points="[50, -5, -131, 35]$[181, -5, 0, 35]$[181, -18, 0, 22]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SlKrYDsREfCFwZ2i48Dr6Q" type="4001" element="_SlJdQDsREfCFwZ2i48Dr6Q" source="_Sb_hQDsREfCFwZ2i48Dr6Q" target="_HB_V5ErlEfCeh5-E9Q3UIA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_SlKrYzsREfCFwZ2i48Dr6Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SlKrZDsREfCFwZ2i48Dr6Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SlKrYTsREfCFwZ2i48Dr6Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SlKrYjsREfCFwZ2i48Dr6Q" points="[0, 0, -126, 0]$[126, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nRKa0E1QEfCo_IWfKKhhfw" type="4001" element="_nQvkEE1QEfCo_IWfKKhhfw" source="_SZxTsDsREfCFwZ2i48Dr6Q" target="_SYmPADsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nRRIgE1QEfCo_IWfKKhhfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nRRIgU1QEfCo_IWfKKhhfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nRKa0U1QEfCo_IWfKKhhfw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nRKa0k1QEfCo_IWfKKhhfw" points="[0, 6, -309, 0]$[309, 6, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nRnGwE1QEfCo_IWfKKhhfw" id="(1.0,0.54)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nRnt0E1QEfCo_IWfKKhhfw" id="(0.046511627906976744,0.4186046511627907)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_odfrEE1QEfCo_IWfKKhhfw" type="4001" element="_odJs0E1QEfCo_IWfKKhhfw" source="_SYmPADsREfCFwZ2i48Dr6Q" target="_SZ-IADsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_odkjkE1QEfCo_IWfKKhhfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_odlKoE1QEfCo_IWfKKhhfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_odg5ME1QEfCo_IWfKKhhfw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_odg5MU1QEfCo_IWfKKhhfw" points="[-23, 14, 4, -145]$[-28, 157, -1, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_od4soE1QEfCo_IWfKKhhfw" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_od4soU1QEfCo_IWfKKhhfw" id="(0.44,0.04)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pJE-sE1QEfCo_IWfKKhhfw" type="4001" element="_pI6moE1QEfCo_IWfKKhhfw" source="_SZ-IADsREfCFwZ2i48Dr6Q" target="_ScWtoDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pJFlwE1QEfCo_IWfKKhhfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pJFlwU1QEfCo_IWfKKhhfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pJE-sU1QEfCo_IWfKKhhfw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pJE-sk1QEfCo_IWfKKhhfw" points="[-3, 19, 36, -290]$[-38, 305, 1, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pJLsYE1QEfCo_IWfKKhhfw" id="(0.62,0.92)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pJLsYU1QEfCo_IWfKKhhfw" id="(0.59,0.08)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DyRKwE3IEfCRZeFygNlKAA" type="4001" element="_DyHZwE3IEfCRZeFygNlKAA" source="_lmF8gE3GEfCRZeFygNlKAA" target="_B1WyIE3IEfCRZeFygNlKAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DyU1IE3IEfCRZeFygNlKAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DyU1IU3IEfCRZeFygNlKAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DyRx0E3IEfCRZeFygNlKAA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DyRx0U3IEfCRZeFygNlKAA" points="[-4, -2, -88, 0]$[51, -1, -33, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DyhpcE3IEfCRZeFygNlKAA" id="(1.0,0.8666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DyhpcU3IEfCRZeFygNlKAA" id="(0.20625,0.525)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_86scsE3MEfCRZeFygNlKAA" type="4001" element="_86foYE3MEfCRZeFygNlKAA" source="_B1WyIE3IEfCRZeFygNlKAA" target="_SX2oIDsREfCFwZ2i48Dr6Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_86yjUE3MEfCRZeFygNlKAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_86yjUU3MEfCRZeFygNlKAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_86scsU3MEfCRZeFygNlKAA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_86scsk3MEfCRZeFygNlKAA" points="[0, 9, -168, 0]$[166, 8, -2, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_86-wkE3MEfCRZeFygNlKAA" id="(1.0,0.35)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_86_XoE3MEfCRZeFygNlKAA" id="(0.09302325581395349,0.4418604651162791)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
